import type { CurriculumTopic, SchoolGrade } from '@/types/domain'

interface CurriculumTopicSeed {
  id: string
  atlasTitle: string
  title: string
  shortDescription: string
  subtopics?: string[]
  tags: string[]
  gradeLevels: SchoolGrade[]
  groupId: string
  prerequisiteTopicIds: string[]
  skillIds: string[]
  estimatedMinutes?: number
}

const curriculumTopicSeeds: CurriculumTopicSeed[] = [
  // 5 клас — математика
  {
    id: 'natural-numbers',
    atlasTitle: 'Читання і запис багаторозрядних чисел',
    title: 'Натуральні числа й арифметика',
    shortDescription: 'Читаємо, порівнюємо й обчислюємо з натуральними числами.',
    tags: ['Натуральні числа', 'Арифметика'],
    gradeLevels: [5],
    groupId: 'grade-5-math',
    prerequisiteTopicIds: [],
    skillIds: ['place-value', 'addition', 'subtraction', 'multiplication', 'division'],
    estimatedMinutes: 12,
  },
  {
    id: 'division-with-remainder',
    atlasTitle: 'Ділення з остачею',
    title: 'Ділення з остачею',
    shortDescription: 'Ділимо натуральні числа, знаходимо остачу та перевіряємо результат.',
    tags: ['Натуральні числа', 'Ділення'],
    gradeLevels: [5],
    groupId: 'grade-5-math',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['division-with-remainder', 'division-check'],
  },
  {
    id: 'powers-natural',
    atlasTitle: 'Степінь із натуральним показником',
    title: 'Квадрат і куб натурального числа',
    shortDescription: 'Записуємо повторне множення степенем та обчислюємо квадрат і куб числа.',
    tags: ['Натуральні числа', 'Степені'],
    gradeLevels: [5],
    groupId: 'grade-5-math',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['power-notation', 'square-number', 'cube-number'],
  },
  {
    id: 'order-of-operations',
    atlasTitle: 'Порядок дій і дужки',
    title: 'Порядок дій',
    shortDescription: 'Дужки, множення й додавання у правильній черзі.',
    tags: ['Числові вирази', 'Порядок дій'],
    gradeLevels: [5],
    groupId: 'grade-5-math',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['operation-order'],
    estimatedMinutes: 12,
  },
  {
    id: 'expressions-formulas-equations',
    atlasTitle: 'Формули',
    title: 'Вирази, формули та рівняння',
    shortDescription: 'Складаємо буквені вирази й формули та знаходимо невідомі компоненти дій.',
    tags: ['Вирази', 'Формули', 'Рівняння'],
    gradeLevels: [5],
    groupId: 'grade-5-math',
    prerequisiteTopicIds: ['order-of-operations'],
    skillIds: ['literal-expressions', 'formula-substitution', 'simple-equations'],
  },
  {
    id: 'measurement-geometry',
    atlasTitle: 'Кут та його вимірювання',
    title: 'Величини та геометричні фігури',
    shortDescription: 'Вимірюємо величини, кути, периметри, площі та об’єми.',
    tags: ['Геометрія', 'Величини', 'Вимірювання'],
    gradeLevels: [5],
    groupId: 'grade-5-geometry',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['unit-conversion', 'angle-measurement', 'perimeter', 'area', 'volume'],
  },
  {
    id: 'coordinate-ray',
    atlasTitle: 'Координатний промінь',
    title: 'Координатний промінь і шкали',
    shortDescription: 'Позначаємо натуральні числа на промені та читаємо значення зі шкал.',
    tags: ['Координати', 'Шкали'],
    gradeLevels: [5],
    groupId: 'grade-5-geometry',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['coordinate-ray', 'read-scales'],
  },
  {
    id: 'tables-diagrams-grade5',
    atlasTitle: 'Таблиці та прості діаграми',
    title: 'Таблиці та прості діаграми',
    shortDescription: 'Збираємо, читаємо й порівнюємо дані в таблицях і простих діаграмах.',
    tags: ['Дані', 'Таблиці', 'Діаграми'],
    gradeLevels: [5],
    groupId: 'grade-5-data',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['read-tables', 'simple-charts', 'compare-data'],
  },
  {
    id: 'fraction-meaning',
    atlasTitle: 'Дріб як частина цілого',
    title: 'Що таке дріб',
    shortDescription: 'Бачимо частину цілого й читаємо звичайні дроби.',
    tags: ['Звичайні дроби', 'Візуальні моделі'],
    gradeLevels: [5],
    groupId: 'grade-5-fractions',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['fraction-model', 'fraction-notation'],
    estimatedMinutes: 12,
  },
  {
    id: 'fraction-types-mixed',
    atlasTitle: 'Правильні й неправильні дроби',
    title: 'Правильні, неправильні дроби та мішані числа',
    shortDescription:
      'Розрізняємо види дробів і переходимо між неправильним дробом та мішаним числом.',
    tags: ['Звичайні дроби', 'Мішані числа'],
    gradeLevels: [5],
    groupId: 'grade-5-fractions',
    prerequisiteTopicIds: ['fraction-meaning'],
    skillIds: ['proper-improper-fractions', 'mixed-number-conversion'],
  },
  {
    id: 'comparing-fractions',
    atlasTitle: 'Порівняння дробів',
    title: 'Порівняння дробів',
    shortDescription: 'Визначаємо, який дріб більший, і позначаємо дроби на прямій.',
    tags: ['Звичайні дроби', 'Порівняння'],
    gradeLevels: [5, 6],
    groupId: 'grade-5-fractions',
    prerequisiteTopicIds: ['fraction-meaning'],
    skillIds: ['compare-fractions'],
    estimatedMinutes: 12,
  },
  {
    id: 'fraction-addition-equal',
    atlasTitle: 'Додавання і віднімання з однаковими знаменниками',
    title: 'Додавання дробів з однаковими знаменниками',
    shortDescription: 'Додаємо й віднімаємо частини однакового розміру.',
    tags: ['Звичайні дроби', 'Додавання й віднімання'],
    gradeLevels: [5],
    groupId: 'grade-5-fractions',
    prerequisiteTopicIds: ['fraction-meaning', 'comparing-fractions'],
    skillIds: ['add-like-fractions', 'subtract-like-fractions'],
    estimatedMinutes: 12,
  },
  {
    id: 'decimals',
    atlasTitle: 'Розряди десяткових дробів',
    title: 'Десяткові дроби',
    shortDescription: 'Читаємо десяткові дроби, порівнюємо їх і працюємо з розрядами.',
    tags: ['Десяткові дроби', 'Розряди'],
    gradeLevels: [5],
    groupId: 'grade-5-decimals',
    prerequisiteTopicIds: ['fraction-meaning'],
    skillIds: ['decimal-place-value', 'compare-decimals'],
  },
  {
    id: 'decimal-operations',
    atlasTitle: 'Додавання і віднімання десяткових дробів',
    title: 'Дії з десятковими дробами',
    shortDescription: 'Додаємо, віднімаємо, множимо й ділимо десяткові дроби.',
    tags: ['Десяткові дроби', 'Обчислення'],
    gradeLevels: [5],
    groupId: 'grade-5-decimals',
    prerequisiteTopicIds: ['decimals', 'order-of-operations'],
    skillIds: [
      'decimal-addition',
      'decimal-subtraction',
      'decimal-multiplication',
      'decimal-division',
    ],
  },
  {
    id: 'arithmetic-mean',
    atlasTitle: 'Середнє арифметичне',
    title: 'Середнє арифметичне',
    shortDescription: 'Знаходимо середнє арифметичне чисел і середнє значення величини.',
    tags: ['Середнє арифметичне', 'Практичні задачі'],
    gradeLevels: [5],
    groupId: 'grade-5-data',
    prerequisiteTopicIds: ['decimal-operations'],
    skillIds: ['arithmetic-mean', 'mean-value-problems'],
  },
  {
    id: 'percentages',
    atlasTitle: 'Поняття відсотка',
    title: 'Відсотки',
    shortDescription: 'Розуміємо відсоток, знаходимо відсоток від числа й число за відсотком.',
    tags: ['Відсотки', 'Практичні задачі'],
    gradeLevels: [5],
    groupId: 'grade-5-percent',
    prerequisiteTopicIds: ['decimal-operations'],
    skillIds: ['percent-meaning', 'percent-of-number'],
  },

  // 6 клас — математика
  {
    id: 'divisibility',
    atlasTitle: 'Ознаки подільності',
    title: 'Подільність натуральних чисел',
    shortDescription: 'Дільники, кратні, прості числа та ознаки подільності.',
    tags: ['Подільність', 'Дільники й кратні'],
    gradeLevels: [6],
    groupId: 'grade-6-numbers',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['factors', 'multiples', 'divisibility-rules', 'prime-factorization'],
    estimatedMinutes: 12,
  },
  {
    id: 'prime-factorization',
    atlasTitle: 'Розклад на прості множники',
    title: 'Розклад числа на прості множники',
    shortDescription:
      'Будуємо дерево множників і записуємо натуральне число добутком простих чисел.',
    tags: ['Подільність', 'Прості числа'],
    gradeLevels: [6],
    groupId: 'grade-6-numbers',
    prerequisiteTopicIds: ['divisibility'],
    skillIds: ['prime-factorization', 'factor-tree'],
  },
  {
    id: 'greatest-common-divisor',
    atlasTitle: 'Найбільший спільний дільник',
    title: 'Найбільший спільний дільник',
    shortDescription: 'Знаходимо НСД чисел за їхніми дільниками та розкладом на прості множники.',
    tags: ['Подільність', 'НСД'],
    gradeLevels: [6],
    groupId: 'grade-6-numbers',
    prerequisiteTopicIds: ['prime-factorization'],
    skillIds: ['greatest-common-divisor', 'coprime-numbers'],
  },
  {
    id: 'least-common-multiple',
    atlasTitle: 'Найменше спільне кратне',
    title: 'Найменше спільне кратне',
    shortDescription: 'Знаходимо НСК чисел і застосовуємо його до задач та спільного знаменника.',
    tags: ['Подільність', 'НСК'],
    gradeLevels: [6],
    groupId: 'grade-6-numbers',
    prerequisiteTopicIds: ['prime-factorization'],
    skillIds: ['least-common-multiple', 'common-multiples'],
  },
  {
    id: 'equivalent-fractions',
    atlasTitle: 'Рівні дроби',
    title: 'Рівні дроби та скорочення',
    shortDescription: 'Знаходимо різні записи тієї самої частини та скорочуємо дроби.',
    tags: ['Звичайні дроби', 'Скорочення'],
    gradeLevels: [6],
    groupId: 'grade-6-fractions',
    prerequisiteTopicIds: ['fraction-meaning', 'divisibility'],
    skillIds: ['equivalent-fractions', 'simplify-fractions'],
  },
  {
    id: 'fraction-addition-different',
    atlasTitle: 'Додавання і віднімання з різними знаменниками',
    title: 'Додавання дробів з різними знаменниками',
    shortDescription: 'Зводимо дроби до спільного знаменника й виконуємо дії.',
    tags: ['Звичайні дроби', 'Спільний знаменник'],
    gradeLevels: [6],
    groupId: 'grade-6-fractions',
    prerequisiteTopicIds: ['equivalent-fractions', 'fraction-addition-equal'],
    skillIds: ['common-denominator', 'add-unlike-fractions', 'subtract-unlike-fractions'],
  },
  {
    id: 'fraction-multiplication',
    atlasTitle: 'Множення дробів',
    title: 'Множення й ділення дробів',
    shortDescription: 'Множимо звичайні дроби та ділимо за допомогою оберненого числа.',
    tags: ['Звичайні дроби', 'Множення й ділення'],
    gradeLevels: [6],
    groupId: 'grade-6-fractions',
    prerequisiteTopicIds: ['equivalent-fractions'],
    skillIds: ['multiply-fractions', 'reciprocal-numbers', 'divide-fractions'],
  },
  {
    id: 'fractions-of-quantity',
    atlasTitle: 'Дріб від числа',
    title: 'Дріб від числа і число за його дробом',
    shortDescription: 'Знаходимо частину величини та відновлюємо ціле за відомою частиною.',
    tags: ['Звичайні дроби', 'Текстові задачі'],
    gradeLevels: [6],
    groupId: 'grade-6-fractions',
    prerequisiteTopicIds: ['fraction-multiplication'],
    skillIds: ['fraction-of-number', 'number-from-fraction'],
  },
  {
    id: 'fraction-decimal-conversion',
    atlasTitle: 'Перетворення звичайних і десяткових дробів',
    title: 'Звичайні й десяткові дроби',
    shortDescription: 'Переходимо між звичайним і десятковим записами числа.',
    tags: ['Звичайні дроби', 'Десяткові дроби', 'Перетворення'],
    gradeLevels: [6],
    groupId: 'grade-6-fractions',
    prerequisiteTopicIds: ['equivalent-fractions', 'decimals'],
    skillIds: ['fraction-to-decimal', 'decimal-to-fraction'],
  },
  {
    id: 'periodic-decimals',
    atlasTitle: 'Скінченні та періодичні десяткові дроби',
    title: 'Скінченні та періодичні десяткові дроби',
    shortDescription: 'Розпізнаємо скінченні й періодичні записи та округлюємо нескінченні дроби.',
    tags: ['Десяткові дроби', 'Періодичні дроби'],
    gradeLevels: [6],
    groupId: 'grade-6-fractions',
    prerequisiteTopicIds: ['fraction-decimal-conversion'],
    skillIds: ['terminating-decimals', 'repeating-decimals'],
  },
  {
    id: 'ratios-proportions',
    atlasTitle: 'Пропорція',
    title: 'Відношення, пропорції та масштаб',
    shortDescription: 'Порівнюємо величини, розв’язуємо пропорції та задачі на масштаб.',
    tags: ['Відношення', 'Пропорції', 'Масштаб'],
    gradeLevels: [6],
    groupId: 'grade-6-ratios',
    prerequisiteTopicIds: ['fraction-multiplication', 'percentages'],
    skillIds: ['ratio', 'proportion', 'scale'],
  },
  {
    id: 'direct-proportion',
    atlasTitle: 'Пряма пропорційність',
    title: 'Пряма пропорційність',
    shortDescription: 'Розпізнаємо прямо пропорційні величини та розв’язуємо задачі пропорцією.',
    tags: ['Пропорції', 'Залежності'],
    gradeLevels: [6],
    groupId: 'grade-6-ratios',
    prerequisiteTopicIds: ['ratios-proportions'],
    skillIds: ['direct-proportion', 'proportional-division'],
  },
  {
    id: 'inverse-proportion',
    atlasTitle: 'Обернена пропорційність',
    title: 'Обернена пропорційність',
    shortDescription:
      'Розпізнаємо обернено пропорційні величини й пояснюємо зміну їхнього добутку.',
    tags: ['Пропорції', 'Залежності'],
    gradeLevels: [6],
    groupId: 'grade-6-ratios',
    prerequisiteTopicIds: ['direct-proportion'],
    skillIds: ['inverse-proportion', 'inverse-proportion-problems'],
  },
  {
    id: 'negative-numbers',
    atlasTitle: 'Від’ємні числа',
    title: 'Від’ємні та раціональні числа',
    shortDescription: 'Числова пряма, протилежні числа, модуль і порівняння.',
    tags: ['Від’ємні числа', 'Раціональні числа'],
    gradeLevels: [6],
    groupId: 'grade-6-rational',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['negative-number-line', 'opposite-numbers', 'absolute-value'],
  },
  {
    id: 'signed-arithmetic',
    atlasTitle: 'Додавання і віднімання цілих чисел',
    title: 'Дії з раціональними числами',
    shortDescription: 'Додаємо, віднімаємо, множимо й ділимо числа з різними знаками.',
    tags: ['Раціональні числа', 'Знаки'],
    gradeLevels: [6],
    groupId: 'grade-6-rational',
    prerequisiteTopicIds: ['negative-numbers'],
    skillIds: ['signed-addition', 'signed-subtraction', 'signed-multiplication', 'signed-division'],
  },
  {
    id: 'grade6-expressions',
    atlasTitle: 'Розкриття дужок',
    title: 'Розкриття дужок і подібні доданки',
    shortDescription:
      'Застосовуємо розподільну властивість, розкриваємо дужки та спрощуємо вирази.',
    tags: ['Алгебра', 'Вирази'],
    gradeLevels: [6],
    groupId: 'grade-6-algebra',
    prerequisiteTopicIds: ['signed-arithmetic'],
    skillIds: ['distributive-property', 'open-parentheses', 'combine-like-terms'],
  },
  {
    id: 'grade6-equations',
    atlasTitle: 'Рівняння як баланс',
    title: 'Рівняння та їхні основні властивості',
    shortDescription: 'Переносимо доданки, ділимо обидві частини та перевіряємо корінь рівняння.',
    tags: ['Алгебра', 'Рівняння'],
    gradeLevels: [6],
    groupId: 'grade-6-algebra',
    prerequisiteTopicIds: ['grade6-expressions'],
    skillIds: ['equation-properties', 'simple-linear-equations', 'equation-check'],
  },
  {
    id: 'circle-measurements-grade6',
    atlasTitle: 'Коло і круг',
    title: 'Коло, круг і сектор',
    shortDescription: 'Розрізняємо елементи кола, обчислюємо довжину кола та площу круга.',
    tags: ['Геометрія', 'Коло'],
    gradeLevels: [6],
    groupId: 'grade-6-geometry',
    prerequisiteTopicIds: ['measurement-geometry'],
    skillIds: ['circle-elements', 'circumference', 'circle-area', 'sector'],
  },
  {
    id: 'solid-figures-grade6',
    atlasTitle: 'Циліндр, конус, куля і сфера',
    title: 'Циліндр, конус, куля і сфера',
    shortDescription: 'Розпізнаємо тіла обертання, їхні елементи та моделі в навколишньому світі.',
    tags: ['Геометрія', 'Просторові фігури'],
    gradeLevels: [6],
    groupId: 'grade-6-geometry',
    prerequisiteTopicIds: ['circle-measurements-grade6'],
    skillIds: ['cylinder', 'cone', 'sphere'],
  },
  {
    id: 'coordinate-plane',
    atlasTitle: 'Координатна площина',
    title: 'Координатна площина',
    shortDescription: 'Будуємо точки за координатами й читаємо координати з рисунка.',
    tags: ['Координати', 'Графіки'],
    gradeLevels: [6],
    groupId: 'grade-6-geometry',
    prerequisiteTopicIds: ['signed-arithmetic'],
    skillIds: ['plot-points', 'read-coordinates'],
  },
  {
    id: 'data-charts-grade6',
    atlasTitle: 'Стовпчасті та кругові діаграми',
    title: 'Стовпчасті та кругові діаграми',
    shortDescription: 'Читаємо, будуємо й порівнюємо подання даних у таблицях і діаграмах.',
    tags: ['Дані', 'Діаграми'],
    gradeLevels: [6],
    groupId: 'grade-6-data',
    prerequisiteTopicIds: ['percentages'],
    skillIds: ['bar-charts', 'pie-charts', 'data-interpretation'],
  },
  {
    id: 'elementary-combinatorics-grade6',
    atlasTitle: 'Найпростіші комбінаторні задачі',
    title: 'Найпростіші комбінаторні задачі',
    shortDescription: 'Перебираємо варіанти системно за допомогою таблиць і дерев можливостей.',
    tags: ['Комбінаторика', 'Логічні задачі'],
    gradeLevels: [6],
    groupId: 'grade-6-data',
    prerequisiteTopicIds: ['data-charts-grade6'],
    skillIds: ['systematic-listing', 'possibility-tree'],
  },

  // 7 клас — алгебра
  {
    id: 'algebraic-expressions',
    atlasTitle: 'Числові й буквені вирази',
    title: 'Цілі алгебраїчні вирази',
    shortDescription: 'Працюємо зі змінними, тотожностями та перетвореннями виразів.',
    tags: ['Алгебра', 'Вирази', 'Тотожності'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['order-of-operations', 'signed-arithmetic'],
    skillIds: ['substitution', 'like-terms', 'identity-transformations'],
  },
  {
    id: 'powers-monomials',
    atlasTitle: 'Властивості степеня з натуральним показником',
    title: 'Степінь із натуральним показником',
    shortDescription: 'Застосовуємо властивості степеня для обчислень і перетворення виразів.',
    tags: ['Алгебра', 'Степені'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['algebraic-expressions', 'powers-natural'],
    skillIds: ['natural-powers', 'power-properties'],
  },
  {
    id: 'monomials',
    atlasTitle: 'Одночлени й многочлени',
    title: 'Одночлени та їх стандартний вигляд',
    shortDescription: 'Визначаємо коефіцієнт і степінь одночлена та виконуємо дії з одночленами.',
    tags: ['Алгебра', 'Одночлени'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['powers-monomials'],
    skillIds: ['monomial-standard-form', 'monomial-degree', 'monomial-operations'],
  },
  {
    id: 'polynomial-operations',
    atlasTitle: 'Додавання та віднімання многочленів',
    title: 'Многочлени та дії з ними',
    shortDescription: 'Додаємо, віднімаємо та множимо многочлени.',
    tags: ['Алгебра', 'Многочлени'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['monomials'],
    skillIds: ['add-polynomials', 'subtract-polynomials'],
  },
  {
    id: 'polynomial-multiplication',
    atlasTitle: 'Множення многочленів',
    title: 'Множення одночлена і многочленів',
    shortDescription:
      'Множимо одночлен на многочлен і многочлен на многочлен за розподільною властивістю.',
    tags: ['Алгебра', 'Многочлени', 'Множення'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['polynomial-operations'],
    skillIds: ['monomial-times-polynomial', 'multiply-polynomials'],
  },
  {
    id: 'common-factor',
    atlasTitle: 'Винесення спільного множника',
    title: 'Винесення спільного множника',
    shortDescription: 'Знаходимо спільний множник членів многочлена та виносимо його за дужки.',
    tags: ['Алгебра', 'Розкладання на множники'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['polynomial-multiplication'],
    skillIds: ['common-factor'],
  },
  {
    id: 'factor-by-grouping',
    atlasTitle: 'Групування',
    title: 'Розкладання на множники групуванням',
    shortDescription: 'Групуємо члени многочлена так, щоб утворити спільний двочленний множник.',
    tags: ['Алгебра', 'Розкладання на множники'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['common-factor'],
    skillIds: ['factor-by-grouping'],
  },
  {
    id: 'polynomial-factorization',
    atlasTitle: 'Формули скороченого множення',
    title: 'Формули скороченого множення та розкладання на множники',
    shortDescription: 'Застосовуємо тотожності та розкладаємо многочлени на множники.',
    tags: ['Алгебра', 'Формули', 'Розкладання на множники'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['factor-by-grouping'],
    skillIds: ['special-products', 'factor-special-products'],
  },
  {
    id: 'linear-equations',
    atlasTitle: 'Багатокрокові лінійні рівняння',
    title: 'Лінійні рівняння',
    shortDescription: 'Крок за кроком знаходимо невідоме та розв’язуємо текстові задачі.',
    tags: ['Алгебра', 'Лінійні рівняння'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['algebraic-expressions'],
    skillIds: ['inverse-operations', 'linear-equations', 'equation-modeling'],
  },
  {
    id: 'linear-functions',
    atlasTitle: 'Лінійна функція',
    title: 'Функції та лінійна функція',
    shortDescription: 'Пов’язуємо таблицю, формулу й графік лінійної залежності.',
    tags: ['Алгебра', 'Функції', 'Графіки'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['linear-equations', 'coordinate-plane'],
    skillIds: ['function-tables', 'linear-graphs', 'slope'],
  },
  {
    id: 'systems-linear-equations',
    atlasTitle: 'Системи лінійних рівнянь',
    title: 'Системи лінійних рівнянь',
    shortDescription: 'Розв’язуємо системи графічно, підстановкою та додаванням.',
    tags: ['Алгебра', 'Системи рівнянь'],
    gradeLevels: [7],
    groupId: 'grade-7-algebra',
    prerequisiteTopicIds: ['linear-functions'],
    skillIds: ['graphical-systems', 'substitution-method', 'elimination-method'],
  },

  // 7 клас — геометрія
  {
    id: 'geometry-foundations-proof',
    atlasTitle: 'Аксіоми, означення і теореми',
    title: 'Означення, аксіоми, теореми та доведення',
    shortDescription:
      'Розрізняємо види математичних тверджень і будуємо послідовне геометричне доведення.',
    tags: ['Геометрія', 'Доведення'],
    gradeLevels: [7],
    groupId: 'grade-7-geometry',
    prerequisiteTopicIds: ['measurement-geometry'],
    skillIds: ['definitions-axioms-theorems', 'proof-structure', 'counterexample'],
  },
  {
    id: 'geometry-axioms-angles',
    atlasTitle: 'Суміжні та вертикальні кути',
    title: 'Найпростіші геометричні фігури та кути',
    shortDescription: 'Працюємо з точками, прямими, відрізками, кутами й першими доведеннями.',
    tags: ['Геометрія', 'Кути', 'Доведення'],
    gradeLevels: [7],
    groupId: 'grade-7-geometry',
    prerequisiteTopicIds: ['geometry-foundations-proof'],
    skillIds: ['geometric-notation', 'adjacent-angles', 'vertical-angles'],
  },
  {
    id: 'triangles-congruence',
    atlasTitle: 'Ознаки рівності трикутників',
    title: 'Трикутники та ознаки рівності',
    shortDescription: 'Доводимо рівність трикутників і досліджуємо їхні елементи.',
    tags: ['Геометрія', 'Трикутники', 'Рівність фігур'],
    gradeLevels: [7],
    groupId: 'grade-7-geometry',
    prerequisiteTopicIds: ['geometry-axioms-angles'],
    skillIds: ['triangle-congruence', 'isosceles-triangle', 'triangle-elements'],
  },
  {
    id: 'triangle-elements',
    atlasTitle: 'Медіана, бісектриса і висота',
    title: 'Медіана, бісектриса і висота трикутника',
    shortDescription: 'Будуємо особливі відрізки трикутника та застосовуємо їхні властивості.',
    tags: ['Геометрія', 'Трикутники'],
    gradeLevels: [7],
    groupId: 'grade-7-geometry',
    prerequisiteTopicIds: ['triangles-congruence'],
    skillIds: ['triangle-median', 'triangle-angle-bisector', 'triangle-altitude'],
  },
  {
    id: 'parallel-lines',
    atlasTitle: 'Кути при паралельних прямих',
    title: 'Паралельні прямі та сума кутів трикутника',
    shortDescription: 'Розпізнаємо паралельні прямі й застосовуємо властивості кутів.',
    tags: ['Геометрія', 'Паралельні прямі', 'Трикутники'],
    gradeLevels: [7],
    groupId: 'grade-7-geometry',
    prerequisiteTopicIds: ['triangle-elements'],
    skillIds: ['parallel-line-angles', 'triangle-angle-sum'],
  },
  {
    id: 'right-triangle-properties-grade7',
    atlasTitle: 'Прямокутний трикутник та його властивості',
    title: 'Прямокутний трикутник та його властивості',
    shortDescription:
      'Застосовуємо властивості гострих кутів, катетів і гіпотенузи прямокутного трикутника.',
    tags: ['Геометрія', 'Прямокутний трикутник'],
    gradeLevels: [7],
    groupId: 'grade-7-geometry',
    prerequisiteTopicIds: ['parallel-lines'],
    skillIds: ['right-triangle-properties', 'thirty-degree-angle-property'],
  },
  {
    id: 'circle-constructions',
    atlasTitle: 'Геометричні побудови',
    title: 'Коло, круг і геометричні побудови',
    shortDescription: 'Досліджуємо коло та виконуємо побудови циркулем і лінійкою.',
    tags: ['Геометрія', 'Коло', 'Побудови'],
    gradeLevels: [7],
    groupId: 'grade-7-geometry',
    prerequisiteTopicIds: ['right-triangle-properties-grade7'],
    skillIds: ['circle-elements', 'locus', 'compass-constructions'],
  },

  // 8 клас — алгебра
  {
    id: 'rational-expressions',
    atlasTitle: 'Раціональні вирази й допустимі значення',
    title: 'Раціональні вирази та дроби',
    shortDescription: 'Знаходимо допустимі значення та виконуємо дії з алгебраїчними дробами.',
    tags: ['Алгебра', 'Раціональні вирази'],
    gradeLevels: [8],
    groupId: 'grade-8-algebra',
    prerequisiteTopicIds: ['polynomial-factorization', 'fraction-multiplication'],
    skillIds: ['domain-restrictions', 'algebraic-fractions'],
  },
  {
    id: 'rational-equations',
    atlasTitle: 'Раціональні рівняння',
    title: 'Раціональні рівняння',
    shortDescription: 'Розв’язуємо рівняння зі змінною у знаменнику та перевіряємо корені.',
    tags: ['Алгебра', 'Раціональні рівняння'],
    gradeLevels: [8],
    groupId: 'grade-8-algebra',
    prerequisiteTopicIds: ['rational-expressions', 'linear-equations'],
    skillIds: ['rational-equations', 'extraneous-roots'],
  },
  {
    id: 'integer-exponents-standard-form',
    atlasTitle: 'Степінь із цілим показником',
    title: 'Степінь із цілим показником і стандартний вигляд числа',
    shortDescription:
      'Працюємо з нульовими й від’ємними показниками та записуємо великі й малі числа стандартно.',
    tags: ['Алгебра', 'Степені', 'Стандартний вигляд'],
    gradeLevels: [8],
    groupId: 'grade-8-algebra',
    prerequisiteTopicIds: ['rational-equations', 'powers-monomials'],
    skillIds: ['integer-exponents', 'negative-exponents', 'scientific-notation'],
  },
  {
    id: 'square-roots',
    atlasTitle: 'Арифметичний квадратний корінь',
    title: 'Квадратні корені',
    shortDescription: 'Обчислюємо арифметичні квадратні корені та перетворюємо вирази.',
    tags: ['Алгебра', 'Квадратні корені'],
    gradeLevels: [8],
    groupId: 'grade-8-algebra',
    prerequisiteTopicIds: ['integer-exponents-standard-form'],
    skillIds: ['square-root', 'root-properties', 'radical-simplification'],
  },
  {
    id: 'real-numbers',
    atlasTitle: 'Ірраціональні та дійсні числа',
    title: 'Ірраціональні та дійсні числа',
    shortDescription: 'Розширюємо числову пряму і наближено оцінюємо ірраціональні числа.',
    tags: ['Алгебра', 'Дійсні числа'],
    gradeLevels: [8],
    groupId: 'grade-8-algebra',
    prerequisiteTopicIds: ['square-roots'],
    skillIds: ['irrational-numbers', 'real-number-line', 'root-estimation'],
  },
  {
    id: 'quadratic-equations',
    atlasTitle: 'Квадратні рівняння',
    title: 'Квадратні рівняння',
    shortDescription: 'Застосовуємо дискримінант, формулу коренів і теорему Вієта.',
    tags: ['Алгебра', 'Квадратні рівняння'],
    gradeLevels: [8],
    groupId: 'grade-8-algebra',
    prerequisiteTopicIds: ['real-numbers', 'polynomial-factorization'],
    skillIds: ['discriminant', 'quadratic-formula', 'vieta-theorem'],
  },
  {
    id: 'quadratic-trinomial',
    atlasTitle: 'Розкладання квадратного тричлена',
    title: 'Квадратний тричлен і його розкладання',
    shortDescription:
      'Знаходимо корені квадратного тричлена й розкладаємо його на лінійні множники.',
    tags: ['Алгебра', 'Квадратний тричлен'],
    gradeLevels: [8],
    groupId: 'grade-8-algebra',
    prerequisiteTopicIds: ['quadratic-equations'],
    skillIds: ['quadratic-trinomial', 'factor-quadratic-trinomial'],
  },

  // 8 клас — геометрія
  {
    id: 'quadrilaterals',
    atlasTitle: 'Чотирикутники та їхні властивості',
    title: 'Чотирикутники',
    shortDescription: 'Досліджуємо паралелограми, прямокутники, ромби, квадрати й трапеції.',
    tags: ['Геометрія', 'Чотирикутники'],
    gradeLevels: [8],
    groupId: 'grade-8-geometry',
    prerequisiteTopicIds: ['parallel-lines'],
    skillIds: ['parallelogram', 'rectangle-rhombus-square', 'trapezoid'],
  },
  {
    id: 'central-inscribed-angles',
    atlasTitle: 'Хорди, дуги й центральні кути',
    title: 'Центральні та вписані кути',
    shortDescription:
      'Пов’язуємо дуги кола з центральними й вписаними кутами та розв’язуємо задачі.',
    tags: ['Геометрія', 'Коло', 'Кути'],
    gradeLevels: [8],
    groupId: 'grade-8-geometry',
    prerequisiteTopicIds: ['quadrilaterals', 'circle-constructions'],
    skillIds: ['central-angle', 'inscribed-angle', 'arc-measure'],
  },
  {
    id: 'inscribed-circumscribed-figures',
    atlasTitle: 'Вписані й описані фігури',
    title: 'Вписані та описані чотирикутники',
    shortDescription: 'Визначаємо умови вписування й описування чотирикутників відносно кола.',
    tags: ['Геометрія', 'Коло', 'Чотирикутники'],
    gradeLevels: [8],
    groupId: 'grade-8-geometry',
    prerequisiteTopicIds: ['central-inscribed-angles'],
    skillIds: ['cyclic-quadrilateral', 'tangential-quadrilateral'],
  },
  {
    id: 'thales-similarity',
    atlasTitle: 'Подібні фігури',
    title: 'Теорема Фалеса та подібність трикутників',
    shortDescription: 'Працюємо з пропорційними відрізками й ознаками подібності.',
    tags: ['Геометрія', 'Подібність', 'Теорема Фалеса'],
    gradeLevels: [8],
    groupId: 'grade-8-geometry',
    prerequisiteTopicIds: ['inscribed-circumscribed-figures', 'ratios-proportions'],
    skillIds: ['thales-theorem', 'triangle-similarity'],
  },
  {
    id: 'right-triangle-metric-relations',
    atlasTitle: 'Метричні співвідношення у прямокутному трикутнику',
    title: 'Метричні співвідношення у прямокутному трикутнику',
    shortDescription: 'Пов’язуємо катети, гіпотенузу, висоту та проєкції катетів.',
    tags: ['Геометрія', 'Прямокутний трикутник'],
    gradeLevels: [8],
    groupId: 'grade-8-geometry',
    prerequisiteTopicIds: ['thales-similarity'],
    skillIds: ['right-triangle-metric-relations', 'leg-projections'],
  },
  {
    id: 'pythagorean-theorem',
    atlasTitle: 'Теорема Піфагора',
    title: 'Теорема Піфагора',
    shortDescription: 'Знаходимо сторони прямокутного трикутника й розв’язуємо практичні задачі.',
    tags: ['Геометрія', 'Прямокутний трикутник'],
    gradeLevels: [8],
    groupId: 'grade-8-geometry',
    prerequisiteTopicIds: ['right-triangle-metric-relations', 'square-roots'],
    skillIds: ['pythagorean-theorem', 'distance-problems'],
  },
  {
    id: 'right-triangles',
    atlasTitle: 'Розв’язування прямокутних трикутників',
    title: 'Розв’язування прямокутних трикутників',
    shortDescription: 'Використовуємо синус, косинус і тангенс гострого кута.',
    tags: ['Геометрія', 'Тригонометрія'],
    gradeLevels: [8],
    groupId: 'grade-8-geometry',
    prerequisiteTopicIds: ['pythagorean-theorem'],
    skillIds: ['acute-trigonometry', 'solve-right-triangles'],
  },
  {
    id: 'polygon-areas',
    atlasTitle: 'Площі трикутників і чотирикутників',
    title: 'Площі многокутників',
    shortDescription: 'Знаходимо площі трикутників, паралелограмів, ромбів і трапецій.',
    tags: ['Геометрія', 'Площа'],
    gradeLevels: [8],
    groupId: 'grade-8-geometry',
    prerequisiteTopicIds: ['quadrilaterals', 'right-triangles'],
    skillIds: ['triangle-area', 'quadrilateral-area'],
  },

  // 9 клас — алгебра
  {
    id: 'linear-inequalities',
    atlasTitle: 'Лінійні нерівності',
    title: 'Числові та лінійні нерівності',
    shortDescription: 'Застосовуємо властивості нерівностей і позначаємо розв’язки проміжками.',
    tags: ['Алгебра', 'Нерівності'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['linear-equations'],
    skillIds: ['inequality-properties', 'linear-inequalities', 'intervals'],
  },
  {
    id: 'systems-linear-inequalities',
    atlasTitle: 'Системи лінійних нерівностей',
    title: 'Системи лінійних нерівностей',
    shortDescription: 'Перетинаємо множини розв’язків кількох нерівностей.',
    tags: ['Алгебра', 'Системи нерівностей'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['linear-inequalities'],
    skillIds: ['inequality-systems', 'interval-intersection'],
  },
  {
    id: 'function-properties-transformations',
    atlasTitle: 'Перетворення графіків',
    title: 'Властивості функцій і перетворення графіків',
    shortDescription:
      'Досліджуємо область визначення, нулі, проміжки знаків і зміни графіка за формулою.',
    tags: ['Алгебра', 'Функції', 'Графіки'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['linear-functions'],
    skillIds: ['function-domain-range', 'function-zeros', 'graph-transformations'],
  },
  {
    id: 'quadratic-function',
    atlasTitle: 'Квадратна функція і парабола',
    title: 'Квадратична функція',
    shortDescription: 'Будуємо параболу й досліджуємо властивості квадратичної функції.',
    tags: ['Алгебра', 'Функції', 'Парабола'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['quadratic-equations', 'function-properties-transformations'],
    skillIds: ['parabola', 'quadratic-graph-properties'],
  },
  {
    id: 'quadratic-inequalities',
    atlasTitle: 'Квадратні нерівності',
    title: 'Квадратні нерівності',
    shortDescription:
      'Розв’язуємо квадратні нерівності за графіком параболи та методом інтервалів.',
    tags: ['Алгебра', 'Нерівності', 'Парабола'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['quadratic-function'],
    skillIds: ['quadratic-inequalities', 'interval-method'],
  },
  {
    id: 'nonlinear-systems',
    atlasTitle: 'Системи нелінійних рівнянь',
    title: 'Системи рівнянь другого степеня',
    shortDescription: 'Розв’язуємо системи, у яких одне або обидва рівняння нелінійні.',
    tags: ['Алгебра', 'Нелінійні системи'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['quadratic-inequalities', 'systems-linear-equations'],
    skillIds: ['nonlinear-systems', 'graph-intersections'],
  },
  {
    id: 'mathematical-modeling',
    atlasTitle: 'Математичне моделювання',
    title: 'Математичне моделювання прикладних задач',
    shortDescription: 'Перекладаємо реальні ситуації мовою функцій, рівнянь, систем і нерівностей.',
    tags: ['Алгебра', 'Моделювання', 'Практичні задачі'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['nonlinear-systems'],
    skillIds: ['build-mathematical-model', 'validate-model', 'interpret-solution'],
  },
  {
    id: 'sequences',
    atlasTitle: 'Числові послідовності',
    title: 'Числові послідовності',
    shortDescription: 'Розпізнаємо закономірності та задаємо послідовності формулами.',
    tags: ['Алгебра', 'Послідовності'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['linear-functions'],
    skillIds: ['sequence-patterns', 'sequence-formulas'],
  },
  {
    id: 'arithmetic-progression',
    atlasTitle: 'Арифметична прогресія',
    title: 'Арифметична прогресія',
    shortDescription: 'Знаходимо члени й суму перших членів арифметичної прогресії.',
    tags: ['Алгебра', 'Прогресії'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['sequences'],
    skillIds: ['arithmetic-progression', 'arithmetic-series'],
  },
  {
    id: 'geometric-progression',
    atlasTitle: 'Геометрична прогресія',
    title: 'Геометрична прогресія',
    shortDescription: 'Працюємо зі знаменником прогресії та сумою її перших членів.',
    tags: ['Алгебра', 'Прогресії'],
    gradeLevels: [9],
    groupId: 'grade-9-algebra',
    prerequisiteTopicIds: ['sequences', 'powers-monomials'],
    skillIds: ['geometric-progression', 'geometric-series'],
  },
  {
    id: 'combinatorics',
    atlasTitle: 'Правило суми і правило добутку',
    title: 'Основи комбінаторики',
    shortDescription: 'Рахуємо кількість варіантів за правилами суми й добутку.',
    tags: ['Комбінаторика', 'Підрахунок'],
    gradeLevels: [9],
    groupId: 'grade-9-data',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['sum-rule', 'product-rule', 'simple-combinations'],
  },
  {
    id: 'data-statistics',
    atlasTitle: 'Таблиці, діаграми та графіки даних',
    title: 'Статистика та подання даних',
    shortDescription: 'Читаємо таблиці й діаграми, знаходимо середнє, медіану, моду та розмах.',
    tags: ['Статистика', 'Дані'],
    gradeLevels: [9],
    groupId: 'grade-9-data',
    prerequisiteTopicIds: ['decimal-operations'],
    skillIds: ['data-charts', 'mean-median-mode', 'range'],
  },
  {
    id: 'probability',
    atlasTitle: 'Класична ймовірність',
    title: 'Основи теорії ймовірностей',
    shortDescription: 'Описуємо випадкові події та обчислюємо класичну ймовірність.',
    tags: ['Ймовірність', 'Випадкові події'],
    gradeLevels: [9],
    groupId: 'grade-9-data',
    prerequisiteTopicIds: ['combinatorics', 'fraction-meaning'],
    skillIds: ['sample-space', 'classical-probability'],
  },

  // 9 клас — геометрія
  {
    id: 'triangle-trigonometry',
    atlasTitle: 'Синус, косинус і тангенс гострого кута',
    title: 'Тригонометричні функції кута',
    shortDescription: 'Поширюємо поняття синуса, косинуса й тангенса на кути до 180°.',
    tags: ['Геометрія', 'Тригонометрія'],
    gradeLevels: [9],
    groupId: 'grade-9-geometry',
    prerequisiteTopicIds: ['right-triangles'],
    skillIds: ['angle-trigonometry', 'trig-values'],
  },
  {
    id: 'triangle-laws',
    atlasTitle: 'Теорема косинусів',
    title: 'Теореми синусів і косинусів',
    shortDescription: 'Розв’язуємо довільні трикутники за сторонами та кутами.',
    tags: ['Геометрія', 'Трикутники', 'Тригонометрія'],
    gradeLevels: [9],
    groupId: 'grade-9-geometry',
    prerequisiteTopicIds: ['triangle-trigonometry'],
    skillIds: ['law-of-sines', 'law-of-cosines', 'solve-triangles'],
  },
  {
    id: 'regular-polygons',
    atlasTitle: 'Правильні многокутники',
    title: 'Правильні многокутники та коло',
    shortDescription: 'Працюємо з правильними многокутниками, вписаними й описаними колами.',
    tags: ['Геометрія', 'Многокутники', 'Коло'],
    gradeLevels: [9],
    groupId: 'grade-9-geometry',
    prerequisiteTopicIds: ['circle-constructions', 'triangle-laws'],
    skillIds: ['regular-polygons', 'inscribed-circumscribed-circles'],
  },
  {
    id: 'circle-measurements-grade9',
    atlasTitle: 'Довжина кола, площа круга і сектора',
    title: 'Довжина кола, площа круга і сектора',
    shortDescription:
      'Обчислюємо довжини дуг, площі секторів і параметри кіл у правильних многокутниках.',
    tags: ['Геометрія', 'Коло', 'Площа'],
    gradeLevels: [9],
    groupId: 'grade-9-geometry',
    prerequisiteTopicIds: ['regular-polygons'],
    skillIds: ['arc-length', 'circle-area', 'sector-area'],
  },
  {
    id: 'coordinate-method',
    atlasTitle: 'Рівняння прямої та кола',
    title: 'Координатний метод у геометрії',
    shortDescription: 'Обчислюємо відстані, координати середини та складаємо рівняння фігур.',
    tags: ['Геометрія', 'Координати'],
    gradeLevels: [9],
    groupId: 'grade-9-geometry',
    prerequisiteTopicIds: ['coordinate-plane', 'linear-functions', 'circle-measurements-grade9'],
    skillIds: ['distance-formula', 'midpoint', 'line-circle-equations'],
  },
  {
    id: 'vectors',
    atlasTitle: 'Вектори на площині',
    title: 'Вектори на площині',
    shortDescription: 'Виконуємо дії з векторами та застосовуємо скалярний добуток.',
    tags: ['Геометрія', 'Вектори'],
    gradeLevels: [9],
    groupId: 'grade-9-geometry',
    prerequisiteTopicIds: ['coordinate-method'],
    skillIds: ['vector-coordinates', 'vector-operations', 'dot-product'],
  },
  {
    id: 'geometric-transformations',
    atlasTitle: 'Геометричні перетворення',
    title: 'Геометричні перетворення',
    shortDescription: 'Досліджуємо симетрію, поворот, паралельне перенесення та гомотетію.',
    tags: ['Геометрія', 'Перетворення', 'Симетрія'],
    gradeLevels: [9],
    groupId: 'grade-9-geometry',
    prerequisiteTopicIds: ['vectors', 'thales-similarity'],
    skillIds: ['symmetry', 'rotation', 'translation', 'homothety'],
  },
]

const topicSubtopics: Readonly<Record<string, string[]>> = {
  // 5 клас
  'natural-numbers': [
    'Цифри, розряди та класи',
    'Читання і запис багаторозрядних чисел',
    'Порівняння та округлення',
    'Додавання, віднімання, множення і ділення',
  ],
  'division-with-remainder': [
    'Неповна частка й остача',
    'Перевірка ділення з остачею',
    'Задачі на розподіл',
  ],
  'powers-natural': ['Степінь як добуток однакових множників', 'Квадрат числа', 'Куб числа'],
  'order-of-operations': [
    'Дії одного й різних ступенів',
    'Дужки у числових виразах',
    'Перевірка та оцінювання результату',
  ],
  'expressions-formulas-equations': [
    'Числові й буквені вирази',
    'Підстановка значень у формулу',
    'Рівняння та невідомі компоненти дій',
  ],
  'measurement-geometry': [
    'Одиниці довжини, площі, об’єму, маси й часу',
    'Точка, пряма, промінь, відрізок і ламана',
    'Кути, многокутники та периметр',
    'Площі прямокутника і квадрата',
    'Паралелепіпед, куб, піраміда, розгортки й об’єм',
  ],
  'coordinate-ray': [
    'Початок відліку й одиничний відрізок',
    'Координата точки',
    'Шкали вимірювальних приладів',
  ],
  'tables-diagrams-grade5': [
    'Читання таблиць',
    'Побудова простої діаграми',
    'Порівняння даних і формулювання висновків',
  ],
  'fraction-meaning': [
    'Чисельник і знаменник',
    'Дріб як частина цілого',
    'Дріб як результат ділення',
    'Частина від числа',
  ],
  'fraction-types-mixed': [
    'Правильні й неправильні дроби',
    'Мішані числа',
    'Перетворення мішаного числа на неправильний дріб і навпаки',
  ],
  'comparing-fractions': [
    'Дроби з однаковими знаменниками',
    'Дроби на координатному промені',
    'Порівняння з одиницею',
  ],
  'fraction-addition-equal': [
    'Додавання дробів з однаковими знаменниками',
    'Віднімання дробів з однаковими знаменниками',
    'Дії з мішаними числами',
  ],
  decimals: [
    'Десятковий запис дробу',
    'Розряди десяткової частини',
    'Порівняння й округлення десяткових дробів',
  ],
  'decimal-operations': [
    'Додавання і віднімання десяткових дробів',
    'Множення десяткових дробів',
    'Ділення десяткових дробів',
    'Множення і ділення на 10, 100, 1000',
  ],
  'arithmetic-mean': [
    'Середнє арифметичне кількох чисел',
    'Середнє значення величини',
    'Практичні задачі на середнє',
  ],
  percentages: [
    'Відсоток як одна сота',
    'Відсоток від числа',
    'Число за його відсотком',
    'Практичні відсоткові розрахунки',
  ],

  // 6 клас
  divisibility: [
    'Дільники й кратні',
    'Ознаки подільності на 2, 3, 5, 9 і 10',
    'Прості та складені числа',
  ],
  'prime-factorization': [
    'Основна теорема арифметики',
    'Дерево множників',
    'Канонічний розклад числа',
  ],
  'greatest-common-divisor': ['Спільні дільники', 'Алгоритм пошуку НСД', 'Взаємно прості числа'],
  'least-common-multiple': ['Спільні кратні', 'Алгоритм пошуку НСК', 'Застосування НСК до задач'],
  'equivalent-fractions': [
    'Основна властивість дробу',
    'Скорочення дробів',
    'Найменший спільний знаменник',
  ],
  'fraction-addition-different': [
    'Зведення до спільного знаменника',
    'Додавання дробів',
    'Віднімання дробів',
    'Дії з мішаними числами',
  ],
  'fraction-multiplication': [
    'Множення дробів',
    'Обернені числа',
    'Ділення дробів',
    'Комбіновані дії зі звичайними дробами',
  ],
  'fractions-of-quantity': [
    'Знаходження дробу від числа',
    'Знаходження числа за значенням його дробу',
    'Текстові задачі з дробами',
  ],
  'fraction-decimal-conversion': [
    'Звичайний дріб у десятковому записі',
    'Десятковий дріб у звичайному записі',
    'Порівняння дробів різних видів',
  ],
  'periodic-decimals': [
    'Скінченний десятковий дріб',
    'Період і запис періодичного дробу',
    'Наближене значення та округлення',
  ],
  'ratios-proportions': [
    'Відношення величин',
    'Основна властивість пропорції',
    'Масштаб',
    'Відсоткове відношення',
  ],
  'direct-proportion': [
    'Коефіцієнт прямої пропорційності',
    'Таблиця прямо пропорційних величин',
    'Пропорційний поділ',
  ],
  'inverse-proportion': [
    'Стала добутку',
    'Таблиця обернено пропорційних величин',
    'Задачі на роботу, швидкість і час',
  ],
  'negative-numbers': [
    'Додатні, від’ємні числа і нуль',
    'Протилежні числа',
    'Модуль числа',
    'Порівняння раціональних чисел',
  ],
  'signed-arithmetic': [
    'Додавання і віднімання чисел із різними знаками',
    'Множення і ділення раціональних чисел',
    'Властивості арифметичних дій',
  ],
  'grade6-expressions': [
    'Розподільна властивість',
    'Розкриття дужок',
    'Коефіцієнт і подібні доданки',
    'Зведення подібних доданків',
  ],
  'grade6-equations': [
    'Корінь рівняння',
    'Основні властивості рівнянь',
    'Лінійні рівняння',
    'Текстові задачі через рівняння',
  ],
  'circle-measurements-grade6': [
    'Центр, радіус, діаметр і хорда',
    'Довжина кола',
    'Площа круга',
    'Круговий сектор',
  ],
  'solid-figures-grade6': ['Циліндр і конус', 'Куля і сфера', 'Елементи й моделі просторових тіл'],
  'coordinate-plane': [
    'Координатні осі та початок координат',
    'Координати точки',
    'Побудова точок і простих фігур',
    'Графіки залежностей',
  ],
  'data-charts-grade6': [
    'Таблиці даних',
    'Стовпчасті діаграми',
    'Кругові діаграми',
    'Аналіз і порівняння даних',
  ],
  'elementary-combinatorics-grade6': [
    'Систематичний перебір',
    'Таблиця варіантів',
    'Дерево можливостей',
  ],

  // 7 клас — алгебра
  'algebraic-expressions': [
    'Числові й буквені вирази',
    'Допустимі значення змінних',
    'Тотожності й тотожні перетворення',
  ],
  'powers-monomials': [
    'Степінь із натуральним показником',
    'Добуток і частка степенів',
    'Степінь добутку, частки та степеня',
  ],
  monomials: [
    'Коефіцієнт і буквена частина',
    'Стандартний вигляд одночлена',
    'Степінь одночлена',
    'Множення та піднесення одночленів до степеня',
  ],
  'polynomial-operations': [
    'Многочлен і його степінь',
    'Подібні члени многочлена',
    'Додавання і віднімання многочленів',
  ],
  'polynomial-multiplication': [
    'Одночлен, помножений на многочлен',
    'Многочлен, помножений на многочлен',
    'Тотожні перетворення добутків',
  ],
  'common-factor': [
    'Пошук спільного числового множника',
    'Пошук спільної буквеної частини',
    'Винесення спільного множника за дужки',
  ],
  'factor-by-grouping': [
    'Групування членів',
    'Спільний двочленний множник',
    'Перевірка розкладання множенням',
  ],
  'polynomial-factorization': [
    'Квадрат суми та квадрат різниці',
    'Різниця квадратів',
    'Сума й різниця кубів',
    'Розкладання за формулами скороченого множення',
  ],
  'linear-equations': [
    'Рівносильні рівняння',
    'Рівняння зі змінною в обох частинах',
    'Рівняння з дужками та дробами',
    'Текстові задачі',
  ],
  'linear-functions': [
    'Поняття функції',
    'Область визначення',
    'Таблиця значень і графік',
    'Лінійна функція та її коефіцієнти',
  ],
  'systems-linear-equations': [
    'Розв’язок системи',
    'Графічний метод',
    'Метод підстановки',
    'Метод додавання',
    'Текстові задачі через системи',
  ],

  // 7 клас — геометрія
  'geometry-foundations-proof': [
    'Неозначувані поняття та означення',
    'Аксіоми й теореми',
    'Пряма й обернена теореми',
    'Контрприклад і структура доведення',
  ],
  'geometry-axioms-angles': [
    'Точка, пряма, промінь і відрізок',
    'Вимірювання відрізків і кутів',
    'Суміжні кути',
    'Вертикальні кути',
  ],
  'triangles-congruence': [
    'Елементи й види трикутників',
    'Перша ознака рівності трикутників',
    'Друга ознака рівності трикутників',
    'Третя ознака рівності трикутників',
    'Рівнобедрений трикутник',
  ],
  'triangle-elements': [
    'Медіана',
    'Бісектриса',
    'Висота',
    'Властивості медіани й бісектриси рівнобедреного трикутника',
  ],
  'parallel-lines': [
    'Ознаки паралельності прямих',
    'Кути при паралельних прямих і січній',
    'Сума кутів трикутника',
    'Зовнішній кут трикутника',
  ],
  'right-triangle-properties-grade7': [
    'Гострі кути прямокутного трикутника',
    'Властивість катета проти кута 30°',
    'Ознаки рівності прямокутних трикутників',
  ],
  'circle-constructions': [
    'Коло, круг, хорда й діаметр',
    'Геометричне місце точок',
    'Серединний перпендикуляр і бісектриса',
    'Побудови циркулем і лінійкою',
  ],

  // 8 клас — алгебра
  'rational-expressions': [
    'Раціональний вираз і допустимі значення',
    'Основна властивість раціонального дробу',
    'Скорочення дробів',
    'Додавання, віднімання, множення й ділення раціональних дробів',
  ],
  'rational-equations': [
    'Область допустимих значень',
    'Зведення до цілого рівняння',
    'Перевірка та сторонні корені',
    'Прикладні задачі',
  ],
  'integer-exponents-standard-form': [
    'Нульовий показник',
    'Від’ємний цілий показник',
    'Властивості степенів',
    'Стандартний вигляд числа',
  ],
  'square-roots': [
    'Арифметичний квадратний корінь',
    'Властивості квадратних коренів',
    'Винесення множника з-під кореня',
    'Тотожні перетворення виразів із коренями',
  ],
  'real-numbers': [
    'Ірраціональні числа',
    'Множина дійсних чисел',
    'Наближене значення квадратного кореня',
  ],
  'quadratic-equations': [
    'Неповні квадратні рівняння',
    'Дискримінант',
    'Формула коренів',
    'Теорема Вієта',
    'Задачі через квадратні рівняння',
  ],
  'quadratic-trinomial': [
    'Корені квадратного тричлена',
    'Формула розкладання',
    'Скорочення раціональних виразів',
  ],

  // 8 клас — геометрія
  quadrilaterals: [
    'Многокутник і сума його кутів',
    'Паралелограм',
    'Прямокутник, ромб і квадрат',
    'Трапеція та її середня лінія',
  ],
  'central-inscribed-angles': ['Дуга й центральний кут', 'Вписаний кут', 'Властивості хорд'],
  'inscribed-circumscribed-figures': [
    'Коло, описане навколо чотирикутника',
    'Коло, вписане в чотирикутник',
    'Ознаки вписаного й описаного чотирикутника',
  ],
  'thales-similarity': [
    'Теорема Фалеса',
    'Пропорційні відрізки',
    'Подібні трикутники',
    'Три ознаки подібності',
    'Властивості медіани й бісектриси',
  ],
  'right-triangle-metric-relations': [
    'Проєкції катетів на гіпотенузу',
    'Висота до гіпотенузи',
    'Метричні формули',
  ],
  'pythagorean-theorem': ['Теорема Піфагора', 'Обернена теорема Піфагора', 'Знаходження відстаней'],
  'right-triangles': [
    'Синус, косинус і тангенс гострого кута',
    'Знаходження сторін',
    'Знаходження кутів',
    'Практичні задачі',
  ],
  'polygon-areas': [
    'Площа паралелограма',
    'Площа трикутника',
    'Площа ромба',
    'Площа трапеції',
    'Відношення площ подібних фігур',
  ],

  // 9 клас — алгебра
  'linear-inequalities': [
    'Числові нерівності та їхні властивості',
    'Лінійна нерівність',
    'Числові проміжки',
    'Подвійні нерівності',
  ],
  'systems-linear-inequalities': [
    'Спільний розв’язок нерівностей',
    'Перетин числових проміжків',
    'Системи та сукупності нерівностей',
  ],
  'function-properties-transformations': [
    'Область визначення і множина значень',
    'Нулі та проміжки знакосталості',
    'Зростання, спадання, найбільше й найменше значення',
    'Паралельне перенесення і масштабування графіків',
  ],
  'quadratic-function': [
    'Графік функції y = ax²',
    'Парабола y = ax² + bx + c',
    'Вершина й вісь симетрії',
    'Нулі та проміжки знакосталості',
  ],
  'quadratic-inequalities': [
    'Розв’язування за графіком параболи',
    'Метод інтервалів',
    'Системи квадратних нерівностей',
  ],
  'nonlinear-systems': [
    'Система рівнянь другого степеня',
    'Графічний метод',
    'Метод підстановки',
    'Текстові задачі',
  ],
  'mathematical-modeling': [
    'Вибір змінних і умов',
    'Побудова рівняння, системи або функції',
    'Розв’язання та перевірка моделі',
    'Інтерпретація відповіді',
  ],
  sequences: [
    'Способи задання послідовності',
    'Формула n-го члена',
    'Рекурентне задання',
    'Закономірності послідовностей',
  ],
  'arithmetic-progression': [
    'Різниця прогресії',
    'Формула n-го члена',
    'Сума перших n членів',
    'Прикладні задачі',
  ],
  'geometric-progression': [
    'Знаменник прогресії',
    'Формула n-го члена',
    'Сума перших n членів',
    'Прикладні задачі',
  ],
  combinatorics: ['Правило суми', 'Правило добутку', 'Систематичний підрахунок варіантів'],
  'data-statistics': [
    'Таблиці, діаграми й графіки',
    'Середнє, медіана й мода',
    'Розмах вибірки',
    'Аналіз достовірності подання даних',
  ],
  probability: [
    'Випадкова подія',
    'Простір елементарних результатів',
    'Класична ймовірність',
    'Протилежні та несумісні події',
  ],

  // 9 клас — геометрія
  'triangle-trigonometry': [
    'Синус, косинус і тангенс кутів від 0° до 180°',
    'Основна тригонометрична тотожність',
    'Значення тригонометричних функцій',
  ],
  'triangle-laws': [
    'Теорема косинусів',
    'Теорема синусів',
    'Розв’язування довільних трикутників',
    'Площа трикутника через синус',
  ],
  'regular-polygons': [
    'Правильний многокутник',
    'Вписане й описане кола',
    'Радіуси правильного многокутника',
    'Побудова правильних многокутників',
  ],
  'circle-measurements-grade9': ['Довжина кола й дуги', 'Площа круга', 'Площа сектора й сегмента'],
  'coordinate-method': [
    'Відстань між двома точками',
    'Координати середини відрізка',
    'Рівняння прямої',
    'Рівняння кола',
  ],
  vectors: [
    'Координати, модуль і напрям вектора',
    'Рівність і колінеарність векторів',
    'Додавання, віднімання та множення на число',
    'Скалярний добуток і кут між векторами',
  ],
  'geometric-transformations': [
    'Осьова й центральна симетрія',
    'Поворот',
    'Паралельне перенесення',
    'Гомотетія та подібність',
  ],
}

export const curriculumTopics: CurriculumTopic[] = curriculumTopicSeeds.map((topic, index) => {
  const { atlasTitle, estimatedMinutes = 14, subtopics, ...seed } = topic
  void atlasTitle

  return {
    ...seed,
    subtopics: subtopics ?? topicSubtopics[seed.id] ?? [seed.title],
    slug: seed.id,
    lessonIds: [`${seed.id}-intro`],
    order: index + 1,
    estimatedMinutes,
  }
})

export const curriculumTopicIdByAtlasTitle: Readonly<Record<string, string>> = Object.freeze(
  Object.fromEntries(curriculumTopicSeeds.map((topic) => [topic.atlasTitle, topic.id])),
)

export function findTopic(topicId: string): CurriculumTopic | undefined {
  return curriculumTopics.find((topic) => topic.id === topicId)
}
