import type { CurriculumTopic } from '@/types/domain'

export const curriculumTopics: CurriculumTopic[] = [
  {
    id: 'natural-numbers',
    slug: 'natural-numbers',
    title: 'Натуральні числа й арифметика',
    shortDescription: 'Додаємо, віднімаємо, множимо й ділимо впевнено.',
    tags: ['Натуральні числа', 'Арифметика'],
    gradeLevels: [5],
    groupId: 'foundation',
    prerequisiteTopicIds: [],
    skillIds: ['addition', 'subtraction', 'multiplication', 'division'],
    lessonIds: ['natural-numbers-foundation'],
    order: 1,
    estimatedMinutes: 12,
  },
  {
    id: 'order-of-operations',
    slug: 'order-of-operations',
    title: 'Порядок дій',
    shortDescription: 'Дужки, множення й додавання у правильній черзі.',
    tags: ['Числові вирази', 'Порядок дій'],
    gradeLevels: [5],
    groupId: 'foundation',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['operation-order'],
    lessonIds: ['order-of-operations-intro'],
    order: 2,
    estimatedMinutes: 12,
  },
  {
    id: 'negative-numbers',
    slug: 'negative-numbers',
    title: 'Від’ємні числа',
    shortDescription: 'Числова пряма, знаки та прості обчислення.',
    tags: ['Від’ємні числа', 'Координатна пряма'],
    gradeLevels: [6],
    groupId: 'foundation',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['negative-number-line', 'signed-arithmetic'],
    lessonIds: ['negative-numbers-intro'],
    order: 3,
    estimatedMinutes: 13,
  },
  {
    id: 'divisibility',
    slug: 'divisibility',
    title: 'Подільність',
    shortDescription: 'Дільники, кратні та ознаки подільності.',
    tags: ['Подільність', 'Дільники й кратні'],
    gradeLevels: [6],
    groupId: 'foundation',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['factors', 'multiples', 'divisibility-rules'],
    lessonIds: ['divisibility-basics'],
    order: 4,
    estimatedMinutes: 12,
  },
  {
    id: 'fraction-meaning',
    slug: 'fraction-meaning',
    title: 'Що таке дріб',
    shortDescription: 'Бачимо частину цілого й читаємо дроби.',
    tags: ['Звичайні дроби', 'Візуальні моделі'],
    gradeLevels: [5],
    groupId: 'fractions',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['fraction-model', 'fraction-notation'],
    lessonIds: ['fraction-meaning-intro'],
    order: 5,
    estimatedMinutes: 12,
  },
  {
    id: 'comparing-fractions',
    slug: 'comparing-fractions',
    title: 'Порівняння дробів',
    shortDescription: 'Визначаємо, який дріб більший.',
    tags: ['Звичайні дроби', 'Порівняння'],
    gradeLevels: [5, 6],
    groupId: 'fractions',
    prerequisiteTopicIds: ['fraction-meaning'],
    skillIds: ['compare-fractions'],
    lessonIds: ['compare-fractions'],
    order: 6,
    estimatedMinutes: 12,
  },
  {
    id: 'equivalent-fractions',
    slug: 'equivalent-fractions',
    title: 'Рівні дроби та скорочення',
    shortDescription: 'Знаходимо різні записи тієї самої частини.',
    tags: ['Звичайні дроби', 'Скорочення'],
    gradeLevels: [6],
    groupId: 'fractions',
    prerequisiteTopicIds: ['fraction-meaning', 'divisibility'],
    skillIds: ['equivalent-fractions', 'simplify-fractions'],
    lessonIds: ['equivalent-fractions'],
    order: 7,
    estimatedMinutes: 15,
  },
  {
    id: 'fraction-addition-equal',
    slug: 'fraction-addition-equal',
    title: 'Додавання дробів з однаковими знаменниками',
    shortDescription: 'Працюємо з частинами однакового розміру.',
    tags: ['Звичайні дроби', 'Додавання й віднімання'],
    gradeLevels: [5],
    groupId: 'fractions',
    prerequisiteTopicIds: ['fraction-meaning'],
    skillIds: ['add-like-fractions', 'subtract-like-fractions'],
    lessonIds: ['fraction-addition-equal'],
    order: 8,
    estimatedMinutes: 12,
  },
  {
    id: 'fraction-addition-different',
    slug: 'fraction-addition-different',
    title: 'Додавання дробів з різними знаменниками',
    shortDescription: 'Зводимо частини до спільного знаменника.',
    tags: ['Звичайні дроби', 'Спільний знаменник'],
    gradeLevels: [6],
    groupId: 'fractions',
    prerequisiteTopicIds: ['equivalent-fractions', 'fraction-addition-equal'],
    skillIds: ['common-denominator', 'add-unlike-fractions'],
    lessonIds: ['fraction-addition-different'],
    order: 9,
    estimatedMinutes: 17,
  },
  {
    id: 'fraction-multiplication',
    slug: 'fraction-multiplication',
    title: 'Множення й ділення дробів',
    shortDescription: 'Множимо частини та ділимо на дріб.',
    tags: ['Звичайні дроби', 'Множення й ділення'],
    gradeLevels: [6],
    groupId: 'fractions',
    prerequisiteTopicIds: ['equivalent-fractions'],
    skillIds: ['multiply-fractions', 'divide-fractions'],
    lessonIds: ['fraction-multiplication'],
    order: 10,
    estimatedMinutes: 16,
  },
  {
    id: 'decimals',
    slug: 'decimals',
    title: 'Десяткові дроби',
    shortDescription: 'Розряди після коми та обчислення.',
    tags: ['Десяткові дроби', 'Обчислення'],
    gradeLevels: [5],
    groupId: 'decimals-percent',
    prerequisiteTopicIds: ['natural-numbers'],
    skillIds: ['decimal-place-value', 'decimal-arithmetic'],
    lessonIds: ['decimals-intro'],
    order: 11,
    estimatedMinutes: 14,
  },
  {
    id: 'fraction-decimal-conversion',
    slug: 'fraction-decimal-conversion',
    title: 'Звичайні й десяткові дроби',
    shortDescription: 'Переходимо між двома формами запису.',
    tags: ['Звичайні дроби', 'Десяткові дроби', 'Перетворення'],
    gradeLevels: [6],
    groupId: 'decimals-percent',
    prerequisiteTopicIds: ['equivalent-fractions', 'decimals'],
    skillIds: ['fraction-to-decimal', 'decimal-to-fraction'],
    lessonIds: ['fraction-decimal-conversion'],
    order: 12,
    estimatedMinutes: 15,
  },
  {
    id: 'percentages',
    slug: 'percentages',
    title: 'Відсотки',
    shortDescription: 'Знаходимо частину від ста у знайомих ситуаціях.',
    tags: ['Відсотки', 'Практичні задачі'],
    gradeLevels: [5],
    groupId: 'decimals-percent',
    prerequisiteTopicIds: ['fraction-decimal-conversion'],
    skillIds: ['percent-meaning', 'percent-of-number'],
    lessonIds: ['percentages-intro'],
    order: 13,
    estimatedMinutes: 15,
  },
  {
    id: 'ratios-proportions',
    slug: 'ratios-proportions',
    title: 'Відношення й пропорції',
    shortDescription: 'Порівнюємо величини та знаходимо невідоме.',
    tags: ['Відношення', 'Пропорції'],
    gradeLevels: [6],
    groupId: 'pre-algebra',
    prerequisiteTopicIds: ['fraction-multiplication', 'percentages'],
    skillIds: ['ratio', 'proportion'],
    lessonIds: ['ratios-proportions'],
    order: 14,
    estimatedMinutes: 16,
  },
  {
    id: 'linear-equations',
    slug: 'linear-equations',
    title: 'Прості лінійні рівняння',
    shortDescription: 'Крок за кроком знаходимо невідоме число.',
    tags: ['Алгебра', 'Лінійні рівняння'],
    gradeLevels: [7],
    groupId: 'pre-algebra',
    prerequisiteTopicIds: ['order-of-operations', 'negative-numbers'],
    skillIds: ['inverse-operations', 'one-step-equations', 'two-step-equations'],
    lessonIds: ['linear-equations-intro'],
    order: 15,
    estimatedMinutes: 17,
  },
]

export function findTopic(topicId: string): CurriculumTopic | undefined {
  return curriculumTopics.find((topic) => topic.id === topicId)
}
