import { grade5TopicIds } from '@/content/curriculum/sequence'
import type { FullLessonContent } from '@/types/domain'

export { grade5TopicIds } from '@/content/curriculum/sequence'

export type Grade5TopicId = (typeof grade5TopicIds)[number]

export const grade5Lessons: Record<Grade5TopicId, FullLessonContent> = {
  'natural-numbers': {
    topicId: 'natural-numbers',
    preview: {
      topicId: 'natural-numbers',
      hook: 'Розряд показує не лише цифру, а й її справжню вагу в числі.',
      question: 'Яке значення має цифра 7 у числі 47 215?',
      choices: ['7', '700', '7 000'],
      correctChoiceIndex: 2,
      explanation: 'Цифра 7 стоїть у розряді тисяч, тому її значення — 7 000.',
      challengeLabel: 'Розкласти число за розрядами',
    },
    introTitle: 'Великі числа стають простими, коли бачиш їхні розряди',
    introText:
      'Навчимося читати, порівнювати й округлювати натуральні числа, а чотири арифметичні дії використовуватимемо як інструменти для задач.',
    mascotMessage: 'Я стежитиму за розрядами, а ти керуватимеш числами.',
    interactionKind: 'groupingBoard',
    explorationTitle: 'Збери три однакові групи по чотири',
    explorationItems: [
      { label: 'Розряди', content: 'Кожна позиція цифри у 10 разів вагоміша за позицію праворуч.' },
      {
        label: 'Порівняння',
        content: 'Спершу порівнюємо кількість цифр, потім — цифри зліва направо.',
      },
      { label: 'Обчислення', content: 'Обернена дія допомагає перевірити знайдений результат.' },
    ],
    guidedTitle: 'Оцінимо й обчислимо 2 748 + 1 965',
    guidedSteps: [
      'Оцінюємо результат: 2 700 + 2 000 ≈ 4 700.',
      'Додаємо за розрядами: 2 748 + 1 900 = 4 648, потім + 65 = 4 713.',
      'Перевіряємо оцінкою: 4 713 близьке до 4 700, отже результат правдоподібний.',
    ],
    summaryText:
      'Ти пов’язала розрядний склад числа з порівнянням, округленням і надійними обчисленнями.',
    exercises: [
      {
        templateId: 'grade5-place-value',
        skillIds: ['place-value'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Знайди значення цифри',
        prompt: 'Яке значення має цифра 6 у числі 364 210?',
        expectedAnswer: '60000',
        hints: ['Назви розряди справа наліво.', 'Цифра 6 стоїть у розряді десятків тисяч.'],
        solutionSteps: ['6 десятків тисяч — це 6 × 10 000.', 'Отже, значення цифри — 60 000.'],
      },
      {
        templateId: 'grade5-rounding',
        skillIds: ['place-value'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Округли число',
        prompt: 'Округли 38 647 до сотень.',
        expectedAnswer: '38600',
        hints: ['Знайди цифру сотень.', 'Подивись на цифру десятків: вона менша за 5.'],
        solutionSteps: [
          'У розряді сотень стоїть 6, а в розряді десятків — 4.',
          '4 < 5, тому отримуємо 38 600.',
        ],
      },
      {
        templateId: 'grade5-natural-operations',
        skillIds: ['addition', 'subtraction', 'multiplication', 'division'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Обчисли зручним способом',
        prompt: '(125 × 8) − 376 = ?',
        expectedAnswer: '624',
        hints: ['Спочатку виконай дію в дужках.', '125 × 8 утворює рівно одну тисячу.'],
        solutionSteps: ['125 × 8 = 1 000.', '1 000 − 376 = 624.'],
      },
    ],
  },

  'division-with-remainder': {
    topicId: 'division-with-remainder',
    preview: {
      topicId: 'division-with-remainder',
      hook: 'Остача показує, скільки предметів не вдалося розкласти у повні рівні групи.',
      question: 'Яка остача від ділення 53 на 8?',
      choices: ['5', '6', '7'],
      correctChoiceIndex: 0,
      explanation: '8 × 6 = 48, а 53 − 48 = 5. Остача 5 менша за дільник 8.',
      challengeLabel: 'Зібрати повні групи',
    },
    introTitle: 'Остача — це точна відповідь на нерівний розподіл',
    introText:
      'Знайдемо неповну частку й остачу, навчимося перевіряти рівність «ділене = дільник × частка + остача» та застосуємо її в задачах.',
    mascotMessage: 'Я складатиму повні коробки, а ти порахуєш те, що залишилося.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Відкрий формулу ділення з остачею',
    explorationItems: [
      {
        label: 'Неповна частка',
        content: 'Це найбільша кількість повних груп, яку можна утворити.',
      },
      { label: 'Остача', content: 'Остача завжди не менша за 0 і менша за дільник.' },
      { label: 'Перевірка', content: 'Дільник × неповна частка + остача = ділене.' },
    ],
    guidedTitle: 'Поділимо 157 на 12',
    guidedSteps: [
      'Шукаємо найбільше кратне 12, що не перевищує 157: 12 × 13 = 156.',
      'Знаходимо остачу: 157 − 156 = 1, отже 157 : 12 = 13 (ост. 1).',
      'Перевіряємо: 12 × 13 + 1 = 157, а 1 < 12.',
    ],
    summaryText:
      'Ти вмієш знаходити неповну частку й остачу та перевіряти результат однією рівністю.',
    exercises: [
      {
        templateId: 'grade5-remainder',
        skillIds: ['division-with-remainder'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Знайди остачу',
        prompt: 'Яка остача від ділення 47 на 6? Введи лише остачу.',
        expectedAnswer: '5',
        hints: ['Знайди найбільше кратне 6, менше за 47.', '6 × 7 = 42.'],
        solutionSteps: ['47 = 6 × 7 + 5.', 'Отже, остача дорівнює 5.'],
      },
      {
        templateId: 'grade5-incomplete-quotient',
        skillIds: ['division-with-remainder'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди неповну частку',
        prompt: '83 : 7. Введи лише неповну частку.',
        expectedAnswer: '11',
        hints: ['Порівняй 7 × 11 і 7 × 12.', '7 × 11 = 77, а 7 × 12 = 84 — забагато.'],
        solutionSteps: ['Найбільше кратне 7, що не перевищує 83, — 77.', '83 : 7 = 11 (ост. 6).'],
      },
      {
        templateId: 'grade5-division-check',
        skillIds: ['division-check'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Віднови ділене',
        prompt: 'Дільник 9, неповна частка 14, остача 4. Знайди ділене.',
        expectedAnswer: '130',
        hints: ['Скористайся формулою перевірки.', 'Помнож 9 на 14 і додай 4.'],
        solutionSteps: ['9 × 14 = 126.', '126 + 4 = 130, отже ділене — 130.'],
      },
    ],
  },

  'powers-natural': {
    topicId: 'powers-natural',
    preview: {
      topicId: 'powers-natural',
      hook: 'Степінь стисло записує добуток однакових множників.',
      question: 'Чому дорівнює 4³?',
      choices: ['12', '16', '64'],
      correctChoiceIndex: 2,
      explanation: '4³ = 4 × 4 × 4 = 64. Показник 3 задає кількість множників.',
      challengeLabel: 'Розгорнути степінь',
    },
    introTitle: 'Степінь перетворює довге множення на короткий запис',
    introText:
      'Розрізнимо основу й показник степеня, обчислимо квадрати та куби чисел і правильно включимо степені до виразів.',
    mascotMessage: 'Я рахуватиму однакові множники, щоб жоден не загубився.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Розбери будову степеня',
    explorationItems: [
      { label: 'Основа', content: 'Основа показує, яке число множимо саме на себе.' },
      { label: 'Показник', content: 'Показник каже, скільки однакових множників у добутку.' },
      { label: 'Квадрат і куб', content: 'Другий степінь називають квадратом, третій — кубом.' },
    ],
    guidedTitle: 'Обчислимо 2³ + 5²',
    guidedSteps: [
      'Розгортаємо 2³ = 2 × 2 × 2 = 8.',
      'Обчислюємо 5² = 5 × 5 = 25.',
      'Додаємо значення степенів: 8 + 25 = 33.',
    ],
    summaryText: 'Ти читаєш степінь як повторне множення та впевнено обчислюєш квадрати й куби.',
    exercises: [
      {
        templateId: 'grade5-square',
        skillIds: ['square-number'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Знайди квадрат',
        prompt: '6² = ?',
        expectedAnswer: '36',
        hints: ['Показник 2 означає два однакові множники.', 'Обчисли 6 × 6.'],
        solutionSteps: ['6² = 6 × 6.', '6 × 6 = 36.'],
      },
      {
        templateId: 'grade5-cube',
        skillIds: ['cube-number'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Знайди куб',
        prompt: '3³ = ?',
        expectedAnswer: '27',
        hints: ['Запиши три множники 3.', 'Спочатку 3 × 3 = 9.'],
        solutionSteps: ['3³ = 3 × 3 × 3.', '9 × 3 = 27.'],
      },
      {
        templateId: 'grade5-power-expression',
        skillIds: ['power-notation', 'square-number', 'cube-number'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Обчисли вираз зі степенями',
        prompt: '2³ + 4² = ?',
        expectedAnswer: '24',
        hints: ['Обчисли кожен степінь окремо.', '2³ = 8, а 4² = 16.'],
        solutionSteps: ['2³ = 8 і 4² = 16.', '8 + 16 = 24.'],
      },
    ],
  },

  'order-of-operations': {
    topicId: 'order-of-operations',
    preview: {
      topicId: 'order-of-operations',
      hook: 'Спільний порядок дій гарантує, що всі отримають однаковий результат.',
      question: 'Що виконуємо першим у виразі 2 + 3 × 4?',
      choices: ['Додавання', 'Множення', 'Будь-яку дію'],
      correctChoiceIndex: 1,
      explanation: 'Спочатку виконуємо множення: 3 × 4 = 12, а потім додаємо 2.',
      challengeLabel: 'Побудувати маршрут виразу',
    },
    introTitle: 'Кожен вираз має свій маршрут',
    introText:
      'Навчимося бачити дужки, степені та дії різних ступенів, а оцінка допоможе помічати помилки ще до завершення обчислень.',
    mascotMessage: 'Я розставлю дорожні знаки, а ти пройдеш вираз у правильній черзі.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Відкрий три правила маршруту',
    explorationItems: [
      { label: 'Дужки', content: 'Дії в дужках виконують першими.' },
      { label: 'Множення й ділення', content: 'Їх виконують до додавання та віднімання.' },
      { label: 'Зліва направо', content: 'Дії одного ступеня виконують у порядку запису.' },
    ],
    guidedTitle: 'Обчислимо 48 − 3 × (7 + 1)',
    guidedSteps: [
      'Спочатку дужки: 7 + 1 = 8.',
      'Потім множення: 3 × 8 = 24.',
      'Нарешті віднімання: 48 − 24 = 24.',
    ],
    summaryText:
      'Ти читаєш вираз як послідовність кроків: дужки, множення й ділення, додавання й віднімання.',
    exercises: [
      {
        templateId: 'grade5-order-basic',
        skillIds: ['operation-order'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Виконай множення першим',
        prompt: '18 + 6 × 4 = ?',
        expectedAnswer: '42',
        hints: ['Додавання зачекає.', 'Спочатку 6 × 4 = 24.'],
        solutionSteps: ['6 × 4 = 24.', '18 + 24 = 42.'],
      },
      {
        templateId: 'grade5-order-parentheses',
        skillIds: ['operation-order'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Почни з дужок',
        prompt: '72 : (5 + 3) + 9 = ?',
        expectedAnswer: '18',
        hints: ['Обчисли суму в дужках.', '72 : 8 = 9.'],
        solutionSteps: ['5 + 3 = 8.', '72 : 8 + 9 = 9 + 9 = 18.'],
      },
      {
        templateId: 'grade5-order-mixed',
        skillIds: ['operation-order'],
        difficulty: 3,
        kind: 'numericInput',
        title: 'Пройди весь маршрут',
        prompt: '100 − 4 × (16 − 7) = ?',
        expectedAnswer: '64',
        hints: ['Почни з 16 − 7.', 'Після дужок виконай множення.'],
        solutionSteps: ['16 − 7 = 9, потім 4 × 9 = 36.', '100 − 36 = 64.'],
      },
    ],
  },

  'expressions-formulas-equations': {
    topicId: 'expressions-formulas-equations',
    preview: {
      topicId: 'expressions-formulas-equations',
      hook: 'Літера в математиці може зберігати число або описувати правило для багатьох чисел.',
      question: 'Як знайти x у рівнянні x + 7 = 19?',
      choices: ['19 + 7', '19 − 7', '19 × 7'],
      correctChoiceIndex: 1,
      explanation: 'Невідомий доданок знаходимо відніманням: x = 19 − 7 = 12.',
      challengeLabel: 'Відновити невідоме',
    },
    introTitle: 'Формула — це правило, а рівняння — математичні терези',
    introText:
      'Складатимемо буквені вирази, підставлятимемо значення у формули та знаходитимемо невідомі компоненти арифметичних дій.',
    mascotMessage: 'Я триматиму терези рівно, а ти відкриєш число за літерою.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Розрізни три математичні записи',
    explorationItems: [
      { label: 'Вираз', content: 'Вираз містить числа, літери й дії, але не має знака рівності.' },
      { label: 'Формула', content: 'Формула описує загальний зв’язок між величинами.' },
      { label: 'Рівняння', content: 'Рівняння — це рівність із невідомим значенням.' },
    ],
    guidedTitle: 'Знайдемо периметр і невідому сторону',
    guidedSteps: [
      'Для прямокутника P = 2 × (a + b). Якщо a = 7, b = 4, то P = 2 × 11 = 22.',
      'Якщо P = 22 і a = 7, маємо 2 × (7 + b) = 22.',
      'Ділимо 22 на 2 й віднімаємо 7: b = 11 − 7 = 4.',
    ],
    summaryText:
      'Ти відрізняєш вираз, формулу й рівняння та вмієш підставляти значення й знаходити невідоме.',
    exercises: [
      {
        templateId: 'grade5-literal-expression',
        skillIds: ['literal-expressions'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Знайди значення виразу',
        prompt: 'Обчисли 3a + 5, якщо a = 7.',
        expectedAnswer: '26',
        hints: ['Заміни a числом 7.', 'Спочатку виконай 3 × 7.'],
        solutionSteps: ['3a + 5 = 3 × 7 + 5.', '21 + 5 = 26.'],
      },
      {
        templateId: 'grade5-formula-substitution',
        skillIds: ['formula-substitution'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Скористайся формулою',
        prompt: 'Шлях s = v × t. Знайди s, якщо v = 12 км/год, t = 3 год.',
        expectedAnswer: '36',
        hints: ['Підстав значення v і t.', 'Помнож 12 на 3.'],
        solutionSteps: ['s = 12 × 3.', 's = 36 км.'],
      },
      {
        templateId: 'grade5-simple-equation',
        skillIds: ['simple-equations'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Розв’яжи рівняння',
        prompt: '5x = 45. Знайди x.',
        expectedAnswer: '9',
        hints: ['Невідомий множник знаходять діленням.', 'Поділи 45 на 5.'],
        solutionSteps: ['x = 45 : 5.', 'x = 9; перевірка: 5 × 9 = 45.'],
      },
    ],
  },

  'measurement-geometry': {
    topicId: 'measurement-geometry',
    preview: {
      topicId: 'measurement-geometry',
      hook: 'Вимірювання перетворює довжину, кут, площу й об’єм на точні числа.',
      question: 'Скільки сантиметрів у 2 метрах?',
      choices: ['20', '200', '2 000'],
      correctChoiceIndex: 1,
      explanation: 'В одному метрі 100 сантиметрів, тому 2 м = 200 см.',
      challengeLabel: 'Зв’язати одиниці',
    },
    introTitle: 'Фігури можна досліджувати за допомогою вимірювань',
    introText:
      'Пов’яжемо одиниці величин, кути, периметр, площу та об’єм, щоб кожна формула описувала реальний об’єкт.',
    mascotMessage: 'Я принесла лінійку й транспортир — вимірюватимемо уважно.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Побач різницю між довжиною, площею та об’ємом',
    explorationItems: [
      {
        label: 'Довжина й периметр',
        content: 'Довжину вимірюють уздовж лінії, периметр — навколо фігури.',
      },
      { label: 'Площа', content: 'Площа показує, скільки квадратних одиниць вкриває поверхню.' },
      { label: 'Об’єм', content: 'Об’єм показує, скільки кубічних одиниць заповнює тіло.' },
    ],
    guidedTitle: 'Дослідимо прямокутний паралелепіпед 5 × 3 × 2',
    guidedSteps: [
      'Периметр основи: 2 × (5 + 3) = 16 см.',
      'Площа основи: 5 × 3 = 15 см².',
      'Об’єм тіла: 5 × 3 × 2 = 30 см³.',
    ],
    summaryText:
      'Ти розрізняєш лінійні, квадратні й кубічні одиниці та добираєш правильну формулу до фігури.',
    exercises: [
      {
        templateId: 'grade5-unit-conversion',
        skillIds: ['unit-conversion'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Перетвори одиниці',
        prompt: 'Скільки сантиметрів у 3 м 45 см?',
        expectedAnswer: '345',
        hints: ['3 м = 300 см.', 'Додай ще 45 см.'],
        solutionSteps: ['3 м = 3 × 100 = 300 см.', '300 + 45 = 345 см.'],
      },
      {
        templateId: 'grade5-perimeter-area',
        skillIds: ['perimeter', 'area'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди площу прямокутника',
        prompt: 'Сторони прямокутника 8 см і 5 см. Знайди площу в см².',
        expectedAnswer: '40',
        hints: ['Площа прямокутника — добуток сторін.', 'Обчисли 8 × 5.'],
        solutionSteps: ['S = a × b.', 'S = 8 × 5 = 40 см².'],
      },
      {
        templateId: 'grade5-volume',
        skillIds: ['volume'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди об’єм',
        prompt: 'Розміри коробки 6 см, 4 см і 3 см. Знайди об’єм у см³.',
        expectedAnswer: '72',
        hints: ['Перемнож усі три виміри.', 'Спочатку 6 × 4 = 24.'],
        solutionSteps: ['V = 6 × 4 × 3.', 'V = 24 × 3 = 72 см³.'],
      },
    ],
  },

  'coordinate-ray': {
    topicId: 'coordinate-ray',
    preview: {
      topicId: 'coordinate-ray',
      hook: 'Одиничний відрізок задає крок, за яким промінь і будь-яка шкала набувають значень.',
      question: 'Один крок на промені дорівнює 5. Яка координата третьої поділки після 0?',
      choices: ['3', '8', '15'],
      correctChoiceIndex: 2,
      explanation: 'Три однакові кроки по 5 дають 3 × 5 = 15.',
      challengeLabel: 'Прочитати шкалу',
    },
    introTitle: 'Координата — це адреса точки на промені',
    introText:
      'Навчимося знаходити початок відліку, визначати ціну поділки й читати координати на променях та шкалах.',
    mascotMessage: 'Я позначу нуль, а ти знайдеш адресу кожної точки.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Налаштуй координатний промінь',
    explorationItems: [
      { label: 'Початок відліку', content: 'Точка O з координатою 0 запускає відлік.' },
      { label: 'Одиничний відрізок', content: 'Відстань між сусідніми значеннями задає масштаб.' },
      { label: 'Координата', content: 'Координата показує, якому числу відповідає точка.' },
    ],
    guidedTitle: 'Знайдемо значення поділки та координату точки',
    guidedSteps: [
      'Між позначками 10 і 30 є 4 однакові проміжки.',
      'Ціна одного проміжку: (30 − 10) : 4 = 5.',
      'Друга поділка після 10 має координату 10 + 2 × 5 = 20.',
    ],
    summaryText:
      'Ти визначаєш ціну поділки та читаєш координати на промені й вимірювальних шкалах.',
    exercises: [
      {
        templateId: 'grade5-coordinate-ray',
        skillIds: ['coordinate-ray'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Знайди координату',
        prompt: 'Одиничний крок дорівнює 4. Яка координата шостої поділки після 0?',
        expectedAnswer: '24',
        hints: ['Кожна поділка додає 4.', 'Помнож 6 на 4.'],
        solutionSteps: ['Шість кроків по 4 — це 6 × 4.', 'Координата точки — 24.'],
      },
      {
        templateId: 'grade5-scale-step',
        skillIds: ['read-scales'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Визнач ціну поділки',
        prompt: 'Між 20 і 50 є 6 однакових проміжків. Яка ціна одного проміжку?',
        expectedAnswer: '5',
        hints: ['Знайди різницю крайніх значень.', 'Поділи 30 на 6.'],
        solutionSteps: ['50 − 20 = 30.', '30 : 6 = 5.'],
      },
      {
        templateId: 'grade5-read-scale',
        skillIds: ['read-scales', 'coordinate-ray'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Прочитай шкалу',
        prompt: 'Шкала починається з 100, ціна поділки 25. Яке значення має четверта поділка?',
        expectedAnswer: '200',
        hints: ['Чотири кроки по 25 дають 100.', 'Додай цей приріст до початкового значення.'],
        solutionSteps: ['4 × 25 = 100.', '100 + 100 = 200.'],
      },
    ],
  },

  'tables-diagrams-grade5': {
    topicId: 'tables-diagrams-grade5',
    preview: {
      topicId: 'tables-diagrams-grade5',
      hook: 'Таблиця зберігає точні значення, а діаграма допомагає швидко побачити їх співвідношення.',
      question: 'У таблиці: пн — 12, вт — 18, ср — 15. У який день значення найбільше?',
      choices: ['Понеділок', 'Вівторок', 'Середа'],
      correctChoiceIndex: 1,
      explanation: 'Порівнюємо значення 12, 18 і 15: найбільше 18 у вівторок.',
      challengeLabel: 'Прочитати дані',
    },
    introTitle: 'Дані розповідають історію, якщо правильно їх прочитати',
    introText:
      'Навчимося знаходити значення в таблиці, читати висоту стовпчиків діаграми, порівнювати дані й формулювати точний висновок.',
    mascotMessage: 'Я не дам рядкам і стовпчикам переплутатися.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Перетвори числа на висновок',
    explorationItems: [
      { label: 'Таблиця', content: 'Спершу знайди потрібний рядок, потім — потрібний стовпчик.' },
      { label: 'Діаграма', content: 'Висота або довжина стовпчика відповідає значенню за шкалою.' },
      { label: 'Висновок', content: 'Висновок має спиратися на конкретне порівняння чисел.' },
    ],
    guidedTitle: 'Проаналізуємо кількість прочитаних сторінок',
    guidedSteps: [
      'Дані за три дні: 18, 25 і 22 сторінки.',
      'Разом прочитано 18 + 25 + 22 = 65 сторінок.',
      'Найбільше значення 25, воно на 25 − 18 = 7 більше за найменше.',
    ],
    summaryText:
      'Ти знаходиш потрібні дані, порівнюєш їх і формулюєш висновки, які підтверджуються числами.',
    exercises: [
      {
        templateId: 'grade5-read-table',
        skillIds: ['read-tables'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Знайди значення в таблиці',
        prompt: 'Продаж квитків: пн — 24, вт — 31, ср — 28. Скільки квитків продали у вівторок?',
        expectedAnswer: '31',
        hints: ['Знайди позначку «вт».', 'Прочитай число поруч із нею.'],
        solutionSteps: ['Рядку «вт» відповідає значення 31.', 'Отже, продали 31 квиток.'],
      },
      {
        templateId: 'grade5-compare-data',
        skillIds: ['compare-data'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Порівняй дані',
        prompt: 'На діаграмі висоти стовпчиків 18 і 27. На скільки друге значення більше?',
        expectedAnswer: '9',
        hints: ['Знайди різницю більшого й меншого значень.', 'Обчисли 27 − 18.'],
        solutionSteps: ['27 − 18 = 9.', 'Друге значення більше на 9.'],
      },
      {
        templateId: 'grade5-chart-total',
        skillIds: ['simple-charts', 'compare-data'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди суму даних',
        prompt: 'Стовпчики діаграми показують 12, 16, 9 і 13 учасників. Скільки учасників разом?',
        expectedAnswer: '50',
        hints: ['Склади значення всіх чотирьох стовпчиків.', 'Зручно об’єднати 12 + 13 і 16 + 9.'],
        solutionSteps: ['12 + 13 = 25 і 16 + 9 = 25.', '25 + 25 = 50 учасників.'],
      },
    ],
  },

  'fraction-meaning': {
    topicId: 'fraction-meaning',
    preview: {
      topicId: 'fraction-meaning',
      hook: 'Дріб називає, скільки рівних частин цілого ми взяли.',
      question: 'Плитку поділили на 6 рівних частин і взяли 3. Який дріб описує взяте?',
      choices: ['3/6', '6/3', '3/3'],
      correctChoiceIndex: 0,
      explanation: 'Усього 6 рівних частин — знаменник, узяли 3 — чисельник.',
      challengeLabel: 'Побудувати модель дробу',
    },
    introTitle: 'Дріб — це частина, яку можна побачити',
    introText:
      'Поділимо ціле на рівні частини, пов’яжемо модель із чисельником і знаменником та використаємо дріб як ділення і як частину числа.',
    mascotMessage: 'Я принесла шоколадну плитку. Ділимо тільки на чесні рівні частини!',
    interactionKind: 'fractionBar',
    explorationTitle: 'Зафарбуй 3 із 6 рівних частин',
    explorationItems: [
      { label: 'Знаменник', content: 'Показує, на скільки рівних частин поділили ціле.' },
      { label: 'Чисельник', content: 'Показує, скільки таких частин узяли.' },
      { label: 'Ділення', content: 'Дріб a/b означає також a : b.' },
    ],
    guidedTitle: 'Як прочитати 3/6',
    guidedSteps: [
      'Рахуємо всі рівні частини: їх 6 — це знаменник.',
      'Рахуємо вибрані частини: їх 3 — це чисельник.',
      'Записуємо 3/6 і бачимо, що це половина цілого.',
    ],
    summaryText:
      'Ти пов’язала чисельник і знаменник із моделлю, діленням та знаходженням частини від числа.',
    exercises: [
      {
        templateId: 'grade5-fraction-model',
        skillIds: ['fraction-model', 'fraction-notation'],
        difficulty: 1,
        kind: 'fractionInput',
        title: 'Запиши дріб',
        prompt: 'Ціле поділили на 8 рівних частин і вибрали 3. Запиши дріб.',
        expectedAnswer: '3/8',
        hints: [
          'Кількість усіх частин записують унизу.',
          'Кількість вибраних частин записують угорі.',
        ],
        solutionSteps: ['Знаменник дорівнює 8.', 'Чисельник дорівнює 3, отже маємо 3/8.'],
      },
      {
        templateId: 'grade5-fraction-division',
        skillIds: ['fraction-notation'],
        difficulty: 1,
        kind: 'fractionInput',
        title: 'Подай ділення дробом',
        prompt: 'Запиши частку 2 : 5 у вигляді дробу.',
        expectedAnswer: '2/5',
        hints: ['Ділене стає чисельником.', 'Дільник стає знаменником.'],
        solutionSteps: ['У діленні 2 : 5 число 2 є діленим.', 'Отже, 2 : 5 = 2/5.'],
      },
      {
        templateId: 'grade5-fraction-of-number',
        skillIds: ['fraction-model'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди частину числа',
        prompt: 'Знайди 3/4 від числа 20.',
        expectedAnswer: '15',
        hints: [
          'Спочатку знайди одну четверту числа.',
          '20 : 4 = 5, потім візьми три такі частини.',
        ],
        solutionSteps: ['1/4 від 20 дорівнює 20 : 4 = 5.', '3/4 від 20 дорівнює 5 × 3 = 15.'],
      },
    ],
  },

  'fraction-types-mixed': {
    topicId: 'fraction-types-mixed',
    preview: {
      topicId: 'fraction-types-mixed',
      hook: 'Неправильний дріб може містити одне ціле або кілька цілих.',
      question: 'Який із дробів неправильний?',
      choices: ['3/7', '7/7', '2/9'],
      correctChoiceIndex: 1,
      explanation: 'У неправильного дробу чисельник не менший за знаменник; 7/7 = 1.',
      challengeLabel: 'Зібрати цілі частини',
    },
    introTitle: 'Неправильні дроби приховують цілі частини',
    introText:
      'Розрізнимо правильні й неправильні дроби, побудуємо мішане число та навчимося переходити між двома записами.',
    mascotMessage: 'Я складатиму повні цілі, а ти порахуєш частини, що залишилися.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Класифікуй дроби за чисельником і знаменником',
    explorationItems: [
      {
        label: 'Правильний дріб',
        content: 'Чисельник менший за знаменник, тому дріб менший за 1.',
      },
      {
        label: 'Неправильний дріб',
        content: 'Чисельник не менший за знаменник, тому дріб не менший за 1.',
      },
      { label: 'Мішане число', content: 'Містить цілу частину та правильний дріб.' },
    ],
    guidedTitle: 'Перетворимо 11/4 на мішане число',
    guidedSteps: [
      'Ділимо 11 на 4: отримуємо неповну частку 2 й остачу 3.',
      'Неповна частка 2 стає цілою частиною.',
      'Остача 3 стає чисельником, знаменник лишається 4: 11/4 = 2 3/4.',
    ],
    summaryText: 'Ти визначаєш вид дробу та переходиш між неправильним дробом і мішаним числом.',
    exercises: [
      {
        templateId: 'grade5-mixed-to-improper',
        skillIds: ['mixed-number-conversion'],
        difficulty: 1,
        kind: 'fractionInput',
        title: 'Перетвори мішане число',
        prompt: 'Запиши 2 1/3 як неправильний дріб.',
        expectedAnswer: '7/3',
        hints: ['Помнож цілу частину на знаменник.', 'До 2 × 3 додай чисельник 1.'],
        solutionSteps: ['2 × 3 + 1 = 7.', 'Знаменник не змінюється: 2 1/3 = 7/3.'],
      },
      {
        templateId: 'grade5-improper-whole-part',
        skillIds: ['proper-improper-fractions', 'mixed-number-conversion'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди цілу частину',
        prompt: 'Яка ціла частина мішаного числа, що дорівнює 17/5?',
        expectedAnswer: '3',
        hints: ['Поділи 17 на 5 з остачею.', '5 × 3 = 15.'],
        solutionSteps: ['17 : 5 = 3 (ост. 2).', '17/5 = 3 2/5, тому ціла частина — 3.'],
      },
      {
        templateId: 'grade5-improper-to-fraction',
        skillIds: ['mixed-number-conversion'],
        difficulty: 2,
        kind: 'fractionInput',
        title: 'Запиши результат неправильним дробом',
        prompt: 'Перетвори 4 3/7 на неправильний дріб.',
        expectedAnswer: '31/7',
        hints: ['Обчисли 4 × 7.', 'Додай чисельник 3.'],
        solutionSteps: ['4 × 7 + 3 = 31.', 'Отже, 4 3/7 = 31/7.'],
      },
    ],
  },

  'comparing-fractions': {
    topicId: 'comparing-fractions',
    preview: {
      topicId: 'comparing-fractions',
      hook: 'Дроби з однаковими знаменниками складаються з частин однакового розміру.',
      question: 'Який дріб більший?',
      choices: ['1/4', '3/4', 'Вони рівні'],
      correctChoiceIndex: 1,
      explanation: 'За однакових знаменників більший чисельник означає більший дріб.',
      challengeLabel: 'Порівняти частини',
    },
    introTitle: 'Координатний промінь перетворює порівняння дробів на відстань',
    introText:
      'Порівняємо дроби з однаковими знаменниками, зіставимо їх з одиницею та розташуємо на координатному промені.',
    mascotMessage: 'Я намалюю однакові частини, а ти знайдеш, яка точка правіше.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Відкрий три способи порівняння',
    explorationItems: [
      { label: 'Однакові знаменники', content: 'Більший чисельник дає більший дріб.' },
      {
        label: 'Порівняння з 1',
        content: 'Правильний дріб менший за 1, неправильний — не менший за 1.',
      },
      { label: 'Промінь', content: 'Із двох точок правіша відповідає більшому числу.' },
    ],
    guidedTitle: 'Розташуємо 2/7, 5/7 і 7/7',
    guidedSteps: [
      'Усі дроби мають однаковий знаменник 7, тому порівнюємо чисельники.',
      '2 < 5 < 7, отже 2/7 < 5/7 < 7/7.',
      'Оскільки 7/7 = 1, обидва інші дроби розташовані лівіше від одиниці.',
    ],
    summaryText:
      'Ти порівнюєш дроби за моделлю, чисельниками та їхнім положенням відносно одиниці.',
    exercises: [
      {
        templateId: 'grade5-compare-like-fractions',
        skillIds: ['compare-fractions'],
        difficulty: 1,
        kind: 'fractionInput',
        title: 'Впиши більший дріб',
        prompt: 'Який дріб більший: 3/8 чи 7/8?',
        expectedAnswer: '7/8',
        hints: ['Знаменники однакові.', 'Порівняй чисельники 3 і 7.'],
        solutionSteps: ['Частини мають однаковий розмір — восьмі.', '7 > 3, тому 7/8 > 3/8.'],
      },
      {
        templateId: 'grade5-fraction-to-one',
        skillIds: ['compare-fractions'],
        difficulty: 1,
        kind: 'fractionInput',
        title: 'Знайди дріб, що дорівнює одиниці',
        prompt: 'Який із дробів 5/9, 9/9, 11/9 дорівнює 1?',
        expectedAnswer: '9/9',
        hints: [
          'Дріб дорівнює 1, коли чисельник і знаменник рівні.',
          'Шукай однакові числа над і під рискою.',
        ],
        solutionSteps: ['У дробі 9/9 чисельник дорівнює знаменнику.', '9/9 = 1.'],
      },
      {
        templateId: 'grade5-fraction-ray',
        skillIds: ['compare-fractions'],
        difficulty: 2,
        kind: 'fractionInput',
        title: 'Знайди правішу точку',
        prompt: 'Яка точка лежить правіше на промені: 4/6 чи 5/6? Впиши її координату.',
        expectedAnswer: '5/6',
        hints: ['Правіше лежить більше число.', 'За однакових знаменників порівняй чисельники.'],
        solutionSteps: ['5 > 4, тому 5/6 > 4/6.', 'Правіша точка має координату 5/6.'],
      },
    ],
  },

  'fraction-addition-equal': {
    topicId: 'fraction-addition-equal',
    preview: {
      topicId: 'fraction-addition-equal',
      hook: 'Частини однакового розміру можна додавати й віднімати, рахуючи їхню кількість.',
      question: 'Скільки буде 2/7 + 3/7?',
      choices: ['5/7', '5/14', '6/7'],
      correctChoiceIndex: 0,
      explanation: 'Знаменник 7 зберігає розмір частин, а чисельники додаємо: 2 + 3 = 5.',
      challengeLabel: 'Скласти рівні частини',
    },
    introTitle: 'Додаємо кількість частин, а не їхній розмір',
    introText:
      'Сформулюємо правила додавання й віднімання дробів з однаковими знаменниками та застосуємо їх до неправильних дробів і мішаних чисел.',
    mascotMessage: 'Я стежитиму, щоб сьомі залишалися сьомими, а ти порахуєш їх разом.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Збережи знаменник',
    explorationItems: [
      { label: 'Додавання', content: 'Чисельники додаємо, спільний знаменник залишаємо.' },
      { label: 'Віднімання', content: 'Чисельники віднімаємо, спільний знаменник залишаємо.' },
      {
        label: 'Мішані числа',
        content: 'Окремо працюємо з цілими та дробовими частинами, за потреби позичаємо ціле.',
      },
    ],
    guidedTitle: 'Обчислимо 2 1/5 + 1 3/5',
    guidedSteps: [
      'Додаємо цілі частини: 2 + 1 = 3.',
      'Додаємо дробові частини: 1/5 + 3/5 = 4/5.',
      'Об’єднуємо результат: 3 4/5.',
    ],
    summaryText:
      'Ти додаєш і віднімаєш дроби зі спільним знаменником та працюєш із мішаними числами.',
    exercises: [
      {
        templateId: 'grade5-add-like-fractions',
        skillIds: ['add-like-fractions'],
        difficulty: 1,
        kind: 'fractionInput',
        title: 'Додай дроби',
        prompt: '3/11 + 5/11 = ?',
        expectedAnswer: '8/11',
        hints: ['Знаменники вже однакові.', 'Додай чисельники 3 і 5.'],
        solutionSteps: ['3/11 + 5/11 = (3 + 5)/11.', 'Отримуємо 8/11.'],
      },
      {
        templateId: 'grade5-subtract-like-fractions',
        skillIds: ['subtract-like-fractions'],
        difficulty: 2,
        kind: 'fractionInput',
        title: 'Відніми дроби',
        prompt: '9/13 − 4/13 = ?',
        expectedAnswer: '5/13',
        hints: ['Знаменник 13 не змінюється.', 'Відніми 4 від 9.'],
        solutionSteps: ['9/13 − 4/13 = (9 − 4)/13.', 'Отримуємо 5/13.'],
      },
      {
        templateId: 'grade5-mixed-like-fractions',
        skillIds: ['add-like-fractions', 'subtract-like-fractions'],
        difficulty: 3,
        kind: 'fractionInput',
        title: 'Обчисли з мішаними числами',
        prompt: 'Обчисли 2 4/7 − 1 6/7. Відповідь запиши неправильним дробом.',
        expectedAnswer: '5/7',
        hints: ['Перетвори обидва числа на неправильні дроби.', '2 4/7 = 18/7, а 1 6/7 = 13/7.'],
        solutionSteps: ['18/7 − 13/7 = 5/7.', 'Отже, відповідь — 5/7.'],
      },
    ],
  },

  decimals: {
    topicId: 'decimals',
    preview: {
      topicId: 'decimals',
      hook: 'Кома відділяє цілу частину від десятих, сотих і тисячних.',
      question: 'Яке число більше?',
      choices: ['0,7', '0,65', 'Вони рівні'],
      correctChoiceIndex: 0,
      explanation: '0,7 = 0,70, а 70 сотих більше за 65 сотих.',
      challengeLabel: 'Порівняти розряди',
    },
    introTitle: 'Десятковий дріб — це розрядний запис частин одиниці',
    introText:
      'Навчимося читати десяткові дроби, визначати розряди після коми, порівнювати числа та округлювати їх.',
    mascotMessage: 'Я вирівняю коми, щоб кожен розряд стояв на своєму місці.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Зазирни праворуч від коми',
    explorationItems: [
      { label: 'Десяті', content: 'Перша цифра після коми показує кількість десятих.' },
      { label: 'Соті й тисячні', content: 'Друга цифра показує соті, третя — тисячні.' },
      {
        label: 'Нулі праворуч',
        content: 'Нулі в кінці дробової частини не змінюють значення: 0,7 = 0,70.',
      },
    ],
    guidedTitle: 'Порівняємо 3,48 і 3,5 та округлимо 3,48',
    guidedSteps: [
      'Вирівнюємо кількість знаків: 3,5 = 3,50.',
      'Цілі частини рівні, але 50 сотих > 48 сотих, тому 3,5 > 3,48.',
      'Для округлення 3,48 до десятих дивимося на 8 сотих: отримуємо 3,5.',
    ],
    summaryText: 'Ти читаєш розряди десяткового дробу, порівнюєш записи та правильно округлюєш.',
    exercises: [
      {
        templateId: 'grade5-decimal-place',
        skillIds: ['decimal-place-value'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Назви цифру розряду',
        prompt: 'Яка цифра стоїть у розряді сотих у числі 12,374?',
        expectedAnswer: '7',
        hints: ['Перша цифра після коми — десяті.', 'Друга цифра після коми — соті.'],
        solutionSteps: [
          'У числі 12,374 цифри після коми: 3 десяті, 7 сотих, 4 тисячні.',
          'Цифра сотих — 7.',
        ],
      },
      {
        templateId: 'grade5-compare-decimals',
        skillIds: ['compare-decimals'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Впиши більше число',
        prompt: 'Яке число більше: 4,08 чи 4,8?',
        expectedAnswer: '4.8',
        hints: ['Запиши 4,8 як 4,80.', 'Порівняй 80 сотих і 8 сотих.'],
        solutionSteps: ['4,8 = 4,80.', '4,80 > 4,08, тому більше число — 4,8.'],
      },
      {
        templateId: 'grade5-round-decimal',
        skillIds: ['decimal-place-value'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Округли десятковий дріб',
        prompt: 'Округли 6,247 до сотих.',
        expectedAnswer: '6.25',
        hints: ['Залиш дві цифри після коми.', 'Цифра тисячних 7, тому соті збільшуються на 1.'],
        solutionSteps: [
          'У розряді сотих стоїть 4, наступна цифра — 7.',
          '7 ≥ 5, тому 6,247 ≈ 6,25.',
        ],
      },
    ],
  },

  'decimal-operations': {
    topicId: 'decimal-operations',
    preview: {
      topicId: 'decimal-operations',
      hook: 'Під час додавання коми вирівнюють розряди, а множення на 10 пересуває кому на один розряд.',
      question: 'Скільки буде 3,7 + 0,45?',
      choices: ['3,115', '4,15', '8,2'],
      correctChoiceIndex: 1,
      explanation: 'Записуємо 3,70 + 0,45 і додаємо відповідні розряди: 4,15.',
      challengeLabel: 'Вирівняти коми',
    },
    introTitle: 'Дії з десятковими дробами спираються на розряди',
    introText:
      'Вирівняємо коми під час додавання й віднімання, простежимо за комою у множенні та діленні й використаємо швидкі дії з 10, 100 і 1000.',
    mascotMessage: 'Я триматиму коми на одній вертикалі, а ти виконаєш дії.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Керуй комою свідомо',
    explorationItems: [
      {
        label: 'Додавання й віднімання',
        content: 'Однакові розряди записують один під одним, кома — під комою.',
      },
      {
        label: 'Множення',
        content:
          'Множимо як натуральні числа, потім відділяємо потрібну кількість десяткових знаків.',
      },
      {
        label: 'Ділення на 10, 100, 1000',
        content: 'Кома рухається ліворуч на 1, 2 або 3 розряди.',
      },
    ],
    guidedTitle: 'Обчислимо 12,6 − 3,75 + 0,4',
    guidedSteps: [
      'Доповнюємо нулями: 12,60 − 3,75 = 8,85.',
      'Вирівнюємо наступну дію: 8,85 + 0,40.',
      'Додаємо відповідні розряди й отримуємо 9,25.',
    ],
    summaryText: 'Ти виконуєш чотири дії з десятковими дробами, спираючись на значення розрядів.',
    exercises: [
      {
        templateId: 'grade5-decimal-add-subtract',
        skillIds: ['decimal-addition', 'decimal-subtraction'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Додай десяткові дроби',
        prompt: '8,35 + 2,7 = ?',
        expectedAnswer: '11.05',
        hints: ['Запиши 2,7 як 2,70.', 'Додай соті, десяті й цілі за розрядами.'],
        solutionSteps: ['8,35 + 2,70.', 'Сума дорівнює 11,05.'],
      },
      {
        templateId: 'grade5-decimal-multiply',
        skillIds: ['decimal-multiplication'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Помнож десятковий дріб',
        prompt: '2,4 × 3 = ?',
        expectedAnswer: '7.2',
        hints: ['Обчисли 24 × 3.', 'У множнику 2,4 один знак після коми.'],
        solutionSteps: ['24 × 3 = 72.', 'Відділяємо один десятковий знак: 7,2.'],
      },
      {
        templateId: 'grade5-decimal-divide',
        skillIds: ['decimal-division'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Поділи десятковий дріб',
        prompt: '45,6 : 10 = ?',
        expectedAnswer: '4.56',
        hints: [
          'Під час ділення на 10 кома рухається на один розряд ліворуч.',
          '45,6 перетворюється на 4,56.',
        ],
        solutionSteps: ['Ділення на 10 зменшує число в 10 разів.', '45,6 : 10 = 4,56.'],
      },
    ],
  },

  'arithmetic-mean': {
    topicId: 'arithmetic-mean',
    preview: {
      topicId: 'arithmetic-mean',
      hook: 'Середнє арифметичне ніби перерозподіляє загальну суму порівну.',
      question: 'Яке середнє арифметичне чисел 6 і 10?',
      choices: ['4', '8', '16'],
      correctChoiceIndex: 1,
      explanation: 'Складаємо числа й ділимо на їх кількість: (6 + 10) : 2 = 8.',
      challengeLabel: 'Вирівняти значення',
    },
    introTitle: 'Середнє показує рівну частку від спільної суми',
    introText:
      'Знайдемо середнє кількох чисел і середнє значення величини та навчимося перевіряти, чи правдоподібний результат.',
    mascotMessage: 'Я складу всі значення докупи, а ти поділиш суму порівну.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Побудуй середнє за два кроки',
    explorationItems: [
      { label: 'Сума', content: 'Спочатку додаємо всі значення.' },
      { label: 'Кількість', content: 'Потім рахуємо, скільки значень додали.' },
      { label: 'Перевірка', content: 'Середнє лежить між найменшим і найбільшим значеннями.' },
    ],
    guidedTitle: 'Знайдемо середню температуру 18°, 21° і 24°',
    guidedSteps: [
      'Знаходимо суму: 18 + 21 + 24 = 63.',
      'Значень три, тому ділимо 63 : 3 = 21.',
      'Перевіряємо: 21 лежить між 18 і 24.',
    ],
    summaryText:
      'Ти знаходиш середнє арифметичне й перевіряєш його за найменшим і найбільшим значеннями.',
    exercises: [
      {
        templateId: 'grade5-mean-two',
        skillIds: ['arithmetic-mean'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Знайди середнє двох чисел',
        prompt: 'Знайди середнє арифметичне чисел 14 і 22.',
        expectedAnswer: '18',
        hints: ['Додай обидва числа.', 'Поділи суму на 2.'],
        solutionSteps: ['14 + 22 = 36.', '36 : 2 = 18.'],
      },
      {
        templateId: 'grade5-mean-several',
        skillIds: ['arithmetic-mean'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди середнє кількох чисел',
        prompt: 'Знайди середнє арифметичне чисел 7, 9, 11 і 13.',
        expectedAnswer: '10',
        hints: ['Знайди суму чотирьох чисел.', 'Поділи суму на 4.'],
        solutionSteps: ['7 + 9 + 11 + 13 = 40.', '40 : 4 = 10.'],
      },
      {
        templateId: 'grade5-mean-value-problem',
        skillIds: ['mean-value-problems'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди середнє значення величини',
        prompt:
          'За три години велосипедист проїхав 12 км, 15 км і 18 км. Яка середня відстань за годину?',
        expectedAnswer: '15',
        hints: ['Склади відстані за всі години.', 'Поділи загальну відстань на 3.'],
        solutionSteps: ['12 + 15 + 18 = 45 км.', '45 : 3 = 15 км за годину в середньому.'],
      },
    ],
  },

  percentages: {
    topicId: 'percentages',
    preview: {
      topicId: 'percentages',
      hook: 'Один відсоток — це одна сота частина цілого.',
      question: '50% плитки шоколаду — це яка частина?',
      choices: ['Половина', 'Чверть', 'Уся плитка'],
      correctChoiceIndex: 0,
      explanation: '50 зі 100 рівних частин — це 50/100 = 1/2.',
      challengeLabel: 'Зібрати 100%',
    },
    introTitle: 'Відсотки дають усім цілим спільну шкалу від 0 до 100',
    introText:
      'Пов’яжемо відсотки зі сотими частинами, знайдемо відсоток від числа та відновимо ціле за відомою відсотковою частиною.',
    mascotMessage: 'Я поділю ціле на сто уявних клітинок, а ти визначиш потрібну частину.',
    interactionKind: 'conceptCards',
    explorationTitle: 'Переклади мову відсотків',
    explorationItems: [
      { label: '1%', content: 'Один відсоток дорівнює 1/100 цілого.' },
      {
        label: 'Відсоток від числа',
        content: 'Знаходимо 1% діленням на 100, потім множимо на потрібну кількість відсотків.',
      },
      {
        label: 'Ціле за відсотком',
        content: 'Відому частину ділимо на кількість відсотків і множимо на 100.',
      },
    ],
    guidedTitle: 'Знайдемо 15% від 240',
    guidedSteps: [
      'Знаходимо 1%: 240 : 100 = 2,4.',
      'Знаходимо 15%: 2,4 × 15 = 36.',
      'Перевіряємо оцінкою: 10% = 24 і 5% = 12, разом 36.',
    ],
    summaryText:
      'Ти читаєш відсоток як соту частину, знаходиш відсоток від числа й відновлюєш ціле.',
    exercises: [
      {
        templateId: 'grade5-percent-meaning',
        skillIds: ['percent-meaning'],
        difficulty: 1,
        kind: 'numericInput',
        title: 'Запиши відсоток десятковим дробом',
        prompt: 'Запиши 35% десятковим дробом.',
        expectedAnswer: '0.35',
        hints: ['35% = 35/100.', 'Поділи 35 на 100.'],
        solutionSteps: ['35% = 35/100.', '35/100 = 0,35.'],
      },
      {
        templateId: 'grade5-percent-of-number',
        skillIds: ['percent-of-number'],
        difficulty: 2,
        kind: 'numericInput',
        title: 'Знайди відсоток від числа',
        prompt: 'Знайди 20% від 150.',
        expectedAnswer: '30',
        hints: ['10% від 150 дорівнює 15.', '20% удвічі більше за 10%.'],
        solutionSteps: ['150 : 100 × 20 = 30.', 'Отже, 20% від 150 дорівнює 30.'],
      },
      {
        templateId: 'grade5-whole-by-percent',
        skillIds: ['percent-of-number'],
        difficulty: 3,
        kind: 'numericInput',
        title: 'Віднови ціле',
        prompt: '25% числа дорівнюють 18. Знайди це число.',
        expectedAnswer: '72',
        hints: ['25% — це одна чверть.', 'Якщо одна чверть дорівнює 18, помнож 18 на 4.'],
        solutionSteps: ['25% = 1/4.', '18 × 4 = 72.'],
      },
    ],
  },
}

export function findGrade5Lesson(topicId: string): FullLessonContent | undefined {
  return grade5Lessons[topicId as Grade5TopicId]
}
